// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module draw (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src_rows_V_read,
        src_cols_V_read,
        src_data_stream_0_V_dout,
        src_data_stream_0_V_empty_n,
        src_data_stream_0_V_read,
        dst_data_stream_0_V_din,
        dst_data_stream_0_V_full_n,
        dst_data_stream_0_V_write,
        dst_data_stream_1_V_din,
        dst_data_stream_1_V_full_n,
        dst_data_stream_1_V_write,
        dst_data_stream_2_V_din,
        dst_data_stream_2_V_full_n,
        dst_data_stream_2_V_write,
        bb_top_V_dout,
        bb_top_V_empty_n,
        bb_top_V_read,
        bb_bottom_V_dout,
        bb_bottom_V_empty_n,
        bb_bottom_V_read,
        bb_left_V_dout,
        bb_left_V_empty_n,
        bb_left_V_read,
        bb_right_V_dout,
        bb_right_V_empty_n,
        bb_right_V_read,
        err_V_dout,
        err_V_empty_n,
        err_V_read,
        val_V_V_dout,
        val_V_V_empty_n,
        val_V_V_read
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] src_rows_V_read;
input  [11:0] src_cols_V_read;
input  [7:0] src_data_stream_0_V_dout;
input   src_data_stream_0_V_empty_n;
output   src_data_stream_0_V_read;
output  [7:0] dst_data_stream_0_V_din;
input   dst_data_stream_0_V_full_n;
output   dst_data_stream_0_V_write;
output  [7:0] dst_data_stream_1_V_din;
input   dst_data_stream_1_V_full_n;
output   dst_data_stream_1_V_write;
output  [7:0] dst_data_stream_2_V_din;
input   dst_data_stream_2_V_full_n;
output   dst_data_stream_2_V_write;
input  [31:0] bb_top_V_dout;
input   bb_top_V_empty_n;
output   bb_top_V_read;
input  [31:0] bb_bottom_V_dout;
input   bb_bottom_V_empty_n;
output   bb_bottom_V_read;
input  [31:0] bb_left_V_dout;
input   bb_left_V_empty_n;
output   bb_left_V_read;
input  [31:0] bb_right_V_dout;
input   bb_right_V_empty_n;
output   bb_right_V_read;
input  [31:0] err_V_dout;
input   err_V_empty_n;
output   err_V_read;
input  [0:0] val_V_V_dout;
input   val_V_V_empty_n;
output   val_V_V_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg src_data_stream_0_V_read;
reg dst_data_stream_0_V_write;
reg dst_data_stream_1_V_write;
reg dst_data_stream_2_V_write;
reg bb_top_V_read;
reg bb_bottom_V_read;
reg bb_left_V_read;
reg bb_right_V_read;
reg err_V_read;
reg val_V_V_read;
reg    ap_done_reg = 1'b0;
reg   [1:0] ap_CS_fsm = 2'b00;
reg   [1:0] state = 2'b00;
reg   [11:0] t_V_reg_205;
reg    ap_sig_bdd_73;
wire   [11:0] i_V_fu_232_p2;
reg   [11:0] i_V_reg_582;
wire   [31:0] tmp_s_fu_238_p1;
reg   [31:0] tmp_s_reg_587;
wire   [0:0] exitcond4_fu_227_p2;
wire   [0:0] exitcond_fu_242_p2;
reg   [0:0] exitcond_reg_593;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_sig_bdd_114;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_593_pp0_it3;
reg    ap_sig_bdd_132;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_593_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_593_pp0_it2;
wire   [11:0] j_V_fu_247_p2;
reg   [11:0] j_V_reg_597;
wire   [0:0] tmp_3_fu_306_p2;
reg   [0:0] tmp_3_reg_611;
reg   [0:0] ap_reg_ppstg_tmp_3_reg_611_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_3_reg_611_pp0_it3;
wire   [0:0] tmp_4_fu_312_p2;
reg   [0:0] tmp_4_reg_618;
wire   [0:0] tmp2_fu_328_p2;
reg   [0:0] tmp2_reg_623;
wire   [0:0] tmp_15_fu_334_p2;
reg   [0:0] tmp_15_reg_628;
wire   [0:0] or_cond7_fu_343_p2;
reg   [0:0] or_cond7_reg_634;
wire   [0:0] tmp_16_fu_347_p2;
reg   [0:0] tmp_16_reg_639;
wire   [0:0] tmp_17_fu_353_p2;
reg   [0:0] tmp_17_reg_645;
wire   [0:0] sel_tmp5_demorgan_fu_364_p2;
reg   [0:0] sel_tmp5_demorgan_reg_650;
wire   [0:0] sel_tmp4_fu_375_p2;
reg   [0:0] sel_tmp4_reg_656;
reg   [0:0] ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3;
wire   [7:0] sel_tmp9_cast_fu_405_p3;
reg   [7:0] sel_tmp9_cast_reg_663;
wire   [0:0] tmp_19_fu_413_p2;
reg   [0:0] tmp_19_reg_668;
wire   [0:0] sel_tmp10_fu_424_p2;
reg   [0:0] sel_tmp10_reg_675;
wire   [7:0] sel_tmp14_fu_429_p3;
reg   [7:0] sel_tmp14_reg_682;
reg   [11:0] t_V_7_reg_194;
reg   [11:0] t_V_phi_fu_209_p4;
wire   [0:0] tmp_V_fiforead_fu_136_p2;
wire   [7:0] pixel_out_val_0_1_fu_497_p3;
wire   [7:0] pixel_out_val_1_1_fu_471_p3;
wire   [7:0] pixel_out_val_2_1_fu_519_p3;
wire   [0:0] or_cond_fu_268_p2;
wire   [0:0] or_cond5_fu_291_p2;
reg   [7:0] pixel_out_val_2_fu_92;
reg   [7:0] pixel_out_val_0_fu_96;
reg   [7:0] pixel_out_val_1_fu_100;
reg   [31:0] state_loc_2_fu_104;
wire   [31:0] extLd_fu_218_p1;
wire   [0:0] p_not_fu_256_p2;
wire   [0:0] tmp_7_fu_262_p2;
wire   [0:0] tmp_8_fu_279_p2;
wire   [0:0] tmp_1_fu_285_p2;
wire   [31:0] tmp_2_fu_302_p1;
wire   [0:0] tmp_5_fu_318_p2;
wire   [0:0] tmp_6_fu_323_p2;
wire   [0:0] sel_tmp3_demorgan_fu_359_p2;
wire   [0:0] sel_tmp_fu_369_p2;
wire   [0:0] sel_tmp7_demorgan_fu_380_p2;
wire   [0:0] sel_tmp7_fu_384_p2;
wire   [0:0] sel_tmp1_fu_395_p2;
wire   [0:0] sel_tmp2_fu_400_p2;
wire   [0:0] sel_tmp8_fu_390_p2;
wire   [0:0] sel_tmp9_fu_419_p2;
wire   [0:0] tmp_20_fu_459_p2;
wire   [7:0] sel_tmp5_fu_452_p3;
wire   [7:0] sel_tmp3_fu_446_p3;
wire   [7:0] sel_tmp6_fu_463_p3;
wire   [7:0] sel_tmp13_fu_489_p1;
wire   [7:0] sel_tmp11_fu_479_p3;
wire   [7:0] sel_tmp13_fu_489_p3;
wire   [7:0] sel_tmp15_fu_505_p3;
wire   [7:0] sel_tmp16_fu_511_p3;
reg   [1:0] ap_NS_fsm;
reg    ap_sig_bdd_482;
reg    ap_sig_bdd_414;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 2'b00;
parameter    ap_ST_st2_fsm_1 = 2'b1;
parameter    ap_ST_pp0_stg0_fsm_2 = 2'b10;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv32_18F = 32'b110001111;
parameter    ap_const_lv32_190 = 32'b110010000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv8_64 = 8'b1100100;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_true = 1'b1;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(exitcond4_fu_227_p2 == ap_const_lv1_0))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == exitcond_fu_242_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond4_fu_227_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == exitcond_fu_242_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond4_fu_227_p2 == ap_const_lv1_0)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == exitcond_fu_242_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond4_fu_227_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond4_fu_227_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond4_fu_227_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_414) begin
        if (ap_sig_bdd_482) begin
            state[0] <= 1'b0;
        end else if ((ap_const_lv1_0 == or_cond_fu_268_p2)) begin
            state[0] <= 1'b1;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_593) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == tmp_V_fiforead_fu_136_p2) & ~(ap_const_lv1_0 == or_cond_fu_268_p2) & ~(ap_const_lv1_0 == or_cond5_fu_291_p2))) begin
        state_loc_2_fu_104[0] <= 1'b0;
    end else if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_593) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == tmp_V_fiforead_fu_136_p2) & (ap_const_lv1_0 == or_cond_fu_268_p2))) begin
        state_loc_2_fu_104[0] <= 1'b1;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_73)) begin
        state_loc_2_fu_104[0] <= extLd_fu_218_p1[0];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == exitcond_fu_242_p2))) begin
        t_V_7_reg_194 <= i_V_reg_582;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_73)) begin
        t_V_7_reg_194 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_593) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        t_V_reg_205 <= j_V_reg_597;
    end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond4_fu_227_p2 == ap_const_lv1_0))) begin
        t_V_reg_205 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        ap_reg_ppstg_exitcond_reg_593_pp0_it1 <= exitcond_reg_593;
        ap_reg_ppstg_exitcond_reg_593_pp0_it2 <= ap_reg_ppstg_exitcond_reg_593_pp0_it1;
        ap_reg_ppstg_exitcond_reg_593_pp0_it3 <= ap_reg_ppstg_exitcond_reg_593_pp0_it2;
        ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3 <= sel_tmp4_reg_656;
        ap_reg_ppstg_tmp_3_reg_611_pp0_it2 <= tmp_3_reg_611;
        ap_reg_ppstg_tmp_3_reg_611_pp0_it3 <= ap_reg_ppstg_tmp_3_reg_611_pp0_it2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        exitcond_reg_593 <= exitcond_fu_242_p2;
        j_V_reg_597 <= j_V_fu_247_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        i_V_reg_582 <= i_V_fu_232_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_593_pp0_it1))) begin
        or_cond7_reg_634 <= or_cond7_fu_343_p2;
        sel_tmp4_reg_656 <= sel_tmp4_fu_375_p2;
        sel_tmp5_demorgan_reg_650 <= sel_tmp5_demorgan_fu_364_p2;
        tmp_16_reg_639 <= tmp_16_fu_347_p2;
        tmp_17_reg_645 <= tmp_17_fu_353_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_593_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        pixel_out_val_0_fu_96 <= pixel_out_val_0_1_fu_497_p3;
        pixel_out_val_1_fu_100 <= pixel_out_val_1_1_fu_471_p3;
        pixel_out_val_2_fu_92 <= pixel_out_val_2_1_fu_519_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_593_pp0_it2))) begin
        sel_tmp10_reg_675 <= sel_tmp10_fu_424_p2;
        sel_tmp14_reg_682[0] <= sel_tmp14_fu_429_p3[0];
sel_tmp14_reg_682[1] <= sel_tmp14_fu_429_p3[1];
sel_tmp14_reg_682[3] <= sel_tmp14_fu_429_p3[3];
sel_tmp14_reg_682[4] <= sel_tmp14_fu_429_p3[4];
sel_tmp14_reg_682[7] <= sel_tmp14_fu_429_p3[7];
        sel_tmp9_cast_reg_663[2] <= sel_tmp9_cast_fu_405_p3[2];
sel_tmp9_cast_reg_663[5] <= sel_tmp9_cast_fu_405_p3[5];
sel_tmp9_cast_reg_663[6] <= sel_tmp9_cast_fu_405_p3[6];
        tmp_19_reg_668 <= tmp_19_fu_413_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_593) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        tmp2_reg_623 <= tmp2_fu_328_p2;
        tmp_15_reg_628 <= tmp_15_fu_334_p2;
        tmp_3_reg_611 <= tmp_3_fu_306_p2;
        tmp_4_reg_618 <= tmp_4_fu_312_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond4_fu_227_p2 == ap_const_lv1_0))) begin
        tmp_s_reg_587[0] <= tmp_s_fu_238_p1[0];
tmp_s_reg_587[1] <= tmp_s_fu_238_p1[1];
tmp_s_reg_587[2] <= tmp_s_fu_238_p1[2];
tmp_s_reg_587[3] <= tmp_s_fu_238_p1[3];
tmp_s_reg_587[4] <= tmp_s_fu_238_p1[4];
tmp_s_reg_587[5] <= tmp_s_fu_238_p1[5];
tmp_s_reg_587[6] <= tmp_s_fu_238_p1[6];
tmp_s_reg_587[7] <= tmp_s_fu_238_p1[7];
tmp_s_reg_587[8] <= tmp_s_fu_238_p1[8];
tmp_s_reg_587[9] <= tmp_s_fu_238_p1[9];
tmp_s_reg_587[10] <= tmp_s_fu_238_p1[10];
tmp_s_reg_587[11] <= tmp_s_fu_238_p1[11];
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_CS_fsm or exitcond4_fu_227_p2)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(exitcond4_fu_227_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond4_fu_227_p2)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(exitcond4_fu_227_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// bb_bottom_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_593 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_132 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_593) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        bb_bottom_V_read = ap_const_logic_1;
    end else begin
        bb_bottom_V_read = ap_const_logic_0;
    end
end

/// bb_left_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_593 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_132 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_593) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        bb_left_V_read = ap_const_logic_1;
    end else begin
        bb_left_V_read = ap_const_logic_0;
    end
end

/// bb_right_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_593 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_132 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_593) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        bb_right_V_read = ap_const_logic_1;
    end else begin
        bb_right_V_read = ap_const_logic_0;
    end
end

/// bb_top_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_593 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_132 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_593) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        bb_top_V_read = ap_const_logic_1;
    end else begin
        bb_top_V_read = ap_const_logic_0;
    end
end

/// dst_data_stream_0_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_593_pp0_it3 or ap_sig_bdd_132 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_593_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        dst_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        dst_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// dst_data_stream_1_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_593_pp0_it3 or ap_sig_bdd_132 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_593_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        dst_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        dst_data_stream_1_V_write = ap_const_logic_0;
    end
end

/// dst_data_stream_2_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_593_pp0_it3 or ap_sig_bdd_132 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_593_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        dst_data_stream_2_V_write = ap_const_logic_1;
    end else begin
        dst_data_stream_2_V_write = ap_const_logic_0;
    end
end

/// err_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_593 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_132 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_593) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        err_V_read = ap_const_logic_1;
    end else begin
        err_V_read = ap_const_logic_0;
    end
end

/// src_data_stream_0_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_593 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_132 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_593) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        src_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        src_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// t_V_phi_fu_209_p4 assign process. ///
always @ (ap_CS_fsm or t_V_reg_205 or exitcond_reg_593 or ap_reg_ppiten_pp0_it1 or j_V_reg_597)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_593) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        t_V_phi_fu_209_p4 = j_V_reg_597;
    end else begin
        t_V_phi_fu_209_p4 = t_V_reg_205;
    end
end

/// val_V_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_593 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_132 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_593) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        val_V_V_read = ap_const_logic_1;
    end else begin
        val_V_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_73 or exitcond4_fu_227_p2 or exitcond_fu_242_p2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_132 or ap_reg_ppiten_pp0_it4)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~ap_sig_bdd_73) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(exitcond4_fu_227_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        ap_ST_pp0_stg0_fsm_2 : 
            if ((~((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == exitcond_fu_242_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == exitcond_fu_242_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_114 assign process. ///
always @ (src_data_stream_0_V_empty_n or bb_top_V_empty_n or bb_bottom_V_empty_n or bb_left_V_empty_n or bb_right_V_empty_n or err_V_empty_n or val_V_V_empty_n or exitcond_reg_593)
begin
    ap_sig_bdd_114 = (((src_data_stream_0_V_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_reg_593)) | ((ap_const_lv1_0 == exitcond_reg_593) & (err_V_empty_n == ap_const_logic_0)) | ((ap_const_lv1_0 == exitcond_reg_593) & (val_V_V_empty_n == ap_const_logic_0)) | ((ap_const_lv1_0 == exitcond_reg_593) & (bb_top_V_empty_n == ap_const_logic_0)) | ((ap_const_lv1_0 == exitcond_reg_593) & (bb_bottom_V_empty_n == ap_const_logic_0)) | ((ap_const_lv1_0 == exitcond_reg_593) & (bb_left_V_empty_n == ap_const_logic_0)) | ((ap_const_lv1_0 == exitcond_reg_593) & (bb_right_V_empty_n == ap_const_logic_0)));
end

/// ap_sig_bdd_132 assign process. ///
always @ (dst_data_stream_0_V_full_n or dst_data_stream_1_V_full_n or dst_data_stream_2_V_full_n or ap_reg_ppstg_exitcond_reg_593_pp0_it3)
begin
    ap_sig_bdd_132 = (((dst_data_stream_0_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_593_pp0_it3)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_593_pp0_it3) & (dst_data_stream_1_V_full_n == ap_const_logic_0)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_593_pp0_it3) & (dst_data_stream_2_V_full_n == ap_const_logic_0)));
end

/// ap_sig_bdd_414 assign process. ///
always @ (ap_CS_fsm or exitcond_reg_593 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_132 or ap_reg_ppiten_pp0_it4 or tmp_V_fiforead_fu_136_p2)
begin
    ap_sig_bdd_414 = ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_593) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_132 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == tmp_V_fiforead_fu_136_p2));
end

/// ap_sig_bdd_482 assign process. ///
always @ (or_cond_fu_268_p2 or or_cond5_fu_291_p2)
begin
    ap_sig_bdd_482 = (~(ap_const_lv1_0 == or_cond_fu_268_p2) & ~(ap_const_lv1_0 == or_cond5_fu_291_p2));
end

/// ap_sig_bdd_73 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_73 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end
assign dst_data_stream_0_V_din = ((sel_tmp10_reg_675)? ap_const_lv8_0: sel_tmp13_fu_489_p3);
assign dst_data_stream_1_V_din = ((sel_tmp10_reg_675)? ap_const_lv8_FF: sel_tmp6_fu_463_p3);
assign dst_data_stream_2_V_din = ((sel_tmp10_reg_675)? ap_const_lv8_0: sel_tmp16_fu_511_p3);
assign exitcond4_fu_227_p2 = (t_V_7_reg_194 == src_rows_V_read? 1'b1: 1'b0);
assign exitcond_fu_242_p2 = (t_V_phi_fu_209_p4 == src_cols_V_read? 1'b1: 1'b0);
assign extLd_fu_218_p1 = $unsigned(state);
assign i_V_fu_232_p2 = (t_V_7_reg_194 + ap_const_lv12_1);
assign j_V_fu_247_p2 = (t_V_phi_fu_209_p4 + ap_const_lv12_1);
assign or_cond5_fu_291_p2 = (tmp_8_fu_279_p2 & tmp_1_fu_285_p2);
assign or_cond7_fu_343_p2 = (tmp2_reg_623 | tmp_4_reg_618);
assign or_cond_fu_268_p2 = (p_not_fu_256_p2 | tmp_7_fu_262_p2);
assign p_not_fu_256_p2 = (state_loc_2_fu_104 != ap_const_lv32_0? 1'b1: 1'b0);
assign pixel_out_val_0_1_fu_497_p3 = ((sel_tmp10_reg_675)? ap_const_lv8_0: sel_tmp13_fu_489_p3);
assign pixel_out_val_1_1_fu_471_p3 = ((sel_tmp10_reg_675)? ap_const_lv8_FF: sel_tmp6_fu_463_p3);
assign pixel_out_val_2_1_fu_519_p3 = ((sel_tmp10_reg_675)? ap_const_lv8_0: sel_tmp16_fu_511_p3);
assign sel_tmp10_fu_424_p2 = (tmp_16_reg_639 & sel_tmp9_fu_419_p2);
assign sel_tmp11_fu_479_p3 = ((tmp_19_reg_668)? ap_const_lv8_0: pixel_out_val_0_fu_96);
assign sel_tmp13_fu_489_p1 = $signed(ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3);
assign sel_tmp13_fu_489_p3 = ((tmp_20_fu_459_p2)? sel_tmp13_fu_489_p1: sel_tmp11_fu_479_p3);
assign sel_tmp14_fu_429_p3 = ((sel_tmp2_fu_400_p2)? ap_const_lv8_64: ap_const_lv8_FF);
assign sel_tmp15_fu_505_p3 = ((tmp_19_reg_668)? sel_tmp14_reg_682: pixel_out_val_2_fu_92);
assign sel_tmp16_fu_511_p3 = ((tmp_20_fu_459_p2)? sel_tmp5_fu_452_p3: sel_tmp15_fu_505_p3);
assign sel_tmp1_fu_395_p2 = (ap_reg_ppstg_tmp_3_reg_611_pp0_it2 ^ ap_const_lv1_1);
assign sel_tmp2_fu_400_p2 = (or_cond7_reg_634 & sel_tmp1_fu_395_p2);
assign sel_tmp3_demorgan_fu_359_p2 = (tmp_3_reg_611 | or_cond7_fu_343_p2);
assign sel_tmp3_fu_446_p3 = ((tmp_19_reg_668)? sel_tmp9_cast_reg_663: pixel_out_val_1_fu_100);
assign sel_tmp4_fu_375_p2 = (tmp_15_reg_628 & sel_tmp_fu_369_p2);
assign sel_tmp5_demorgan_fu_364_p2 = (sel_tmp3_demorgan_fu_359_p2 | tmp_15_reg_628);
assign sel_tmp5_fu_452_p3 = ((ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3)? ap_const_lv8_FF: ap_const_lv8_64);
assign sel_tmp6_fu_463_p3 = ((tmp_20_fu_459_p2)? sel_tmp5_fu_452_p3: sel_tmp3_fu_446_p3);
assign sel_tmp7_demorgan_fu_380_p2 = (sel_tmp5_demorgan_reg_650 | tmp_16_reg_639);
assign sel_tmp7_fu_384_p2 = (sel_tmp7_demorgan_fu_380_p2 ^ ap_const_lv1_1);
assign sel_tmp8_fu_390_p2 = (tmp_17_reg_645 & sel_tmp7_fu_384_p2);
assign sel_tmp9_cast_fu_405_p3 = ((sel_tmp2_fu_400_p2)? ap_const_lv8_64: ap_const_lv8_0);
assign sel_tmp9_fu_419_p2 = (sel_tmp5_demorgan_reg_650 ^ ap_const_lv1_1);
assign sel_tmp_fu_369_p2 = (sel_tmp3_demorgan_fu_359_p2 ^ ap_const_lv1_1);
assign tmp2_fu_328_p2 = (tmp_5_fu_318_p2 | tmp_6_fu_323_p2);
assign tmp_15_fu_334_p2 = (src_data_stream_0_V_dout == ap_const_lv8_FF? 1'b1: 1'b0);
assign tmp_16_fu_347_p2 = (state_loc_2_fu_104 == ap_const_lv32_1? 1'b1: 1'b0);
assign tmp_17_fu_353_p2 = (state_loc_2_fu_104 == ap_const_lv32_0? 1'b1: 1'b0);
assign tmp_19_fu_413_p2 = (sel_tmp2_fu_400_p2 | sel_tmp8_fu_390_p2);
assign tmp_1_fu_285_p2 = (err_V_dout > ap_const_lv32_190? 1'b1: 1'b0);
assign tmp_20_fu_459_p2 = (ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3 | ap_reg_ppstg_tmp_3_reg_611_pp0_it3);
assign tmp_2_fu_302_p1 = $unsigned(t_V_reg_205);
assign tmp_3_fu_306_p2 = (tmp_2_fu_302_p1 == bb_left_V_dout? 1'b1: 1'b0);
assign tmp_4_fu_312_p2 = (tmp_2_fu_302_p1 == bb_right_V_dout? 1'b1: 1'b0);
assign tmp_5_fu_318_p2 = (tmp_s_reg_587 == bb_top_V_dout? 1'b1: 1'b0);
assign tmp_6_fu_323_p2 = (tmp_s_reg_587 == bb_bottom_V_dout? 1'b1: 1'b0);
assign tmp_7_fu_262_p2 = (err_V_dout > ap_const_lv32_18F? 1'b1: 1'b0);
assign tmp_8_fu_279_p2 = (state_loc_2_fu_104 == ap_const_lv32_1? 1'b1: 1'b0);
assign tmp_V_fiforead_fu_136_p2 = val_V_V_dout;
assign tmp_s_fu_238_p1 = $unsigned(t_V_7_reg_194);
always @ (posedge ap_clk)
begin
    state[1] <= 1'b0;
    tmp_s_reg_587[31:12] <= 20'b00000000000000000000;
    sel_tmp9_cast_reg_663[1:0] <= 2'b00;
    sel_tmp9_cast_reg_663[4:3] <= 2'b00;
    sel_tmp9_cast_reg_663[7] <= 1'b0;
    sel_tmp14_reg_682[2] <= 1'b1;
    sel_tmp14_reg_682[6:5] <= 2'b11;
    state_loc_2_fu_104[31:1] <= 31'b0000000000000000000000000000000;
end



endmodule //draw

