// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bounding_box (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src_rows_V_read,
        src_cols_V_read,
        src_data_stream_0_V_dout,
        src_data_stream_0_V_empty_n,
        src_data_stream_0_V_read,
        dst_data_stream_0_V_din,
        dst_data_stream_0_V_full_n,
        dst_data_stream_0_V_write,
        bb_top_V_din,
        bb_top_V_full_n,
        bb_top_V_write,
        bb_bottom_V_din,
        bb_bottom_V_full_n,
        bb_bottom_V_write,
        bb_left_V_din,
        bb_left_V_full_n,
        bb_left_V_write,
        bb_right_V_din,
        bb_right_V_full_n,
        bb_right_V_write
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] src_rows_V_read;
input  [11:0] src_cols_V_read;
input  [7:0] src_data_stream_0_V_dout;
input   src_data_stream_0_V_empty_n;
output   src_data_stream_0_V_read;
output  [7:0] dst_data_stream_0_V_din;
input   dst_data_stream_0_V_full_n;
output   dst_data_stream_0_V_write;
output  [31:0] bb_top_V_din;
input   bb_top_V_full_n;
output   bb_top_V_write;
output  [31:0] bb_bottom_V_din;
input   bb_bottom_V_full_n;
output   bb_bottom_V_write;
output  [31:0] bb_left_V_din;
input   bb_left_V_full_n;
output   bb_left_V_write;
output  [31:0] bb_right_V_din;
input   bb_right_V_full_n;
output   bb_right_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg src_data_stream_0_V_read;
reg dst_data_stream_0_V_write;
reg bb_top_V_write;
reg bb_bottom_V_write;
reg bb_left_V_write;
reg bb_right_V_write;
reg    ap_done_reg = 1'b0;
reg   [1:0] ap_CS_fsm = 2'b00;
reg   [63:0] guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns = 64'b0000000000000000000000000000000000000000000000000000000000000000;
reg   [31:0] p_bottom = 32'b00000000000000000000000000000000;
reg   [63:0] guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns_1 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
reg   [31:0] p_right = 32'b00000000000000000000000000000000;
reg   [31:0] p_top = 32'b00000000000000000000000000000000;
reg   [31:0] p_left = 32'b00000000000000000000000000000000;
reg   [11:0] t_V_reg_227;
reg   [11:0] ap_reg_ppstg_t_V_reg_227_pp0_it1;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg   [0:0] exitcond_reg_772;
reg    ap_sig_bdd_67;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_772_pp0_it4;
reg    ap_sig_bdd_93;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg   [11:0] ap_reg_ppstg_t_V_reg_227_pp0_it2;
reg    ap_sig_bdd_106;
wire   [12:0] op2_assign_8_fu_328_p2;
reg   [12:0] op2_assign_8_reg_722;
wire   [12:0] op2_assign_9_fu_338_p2;
reg   [12:0] op2_assign_9_reg_727;
wire   [12:0] op2_assign_fu_344_p2;
reg   [12:0] op2_assign_reg_732;
wire   [12:0] op2_assign_3_fu_350_p2;
reg   [12:0] op2_assign_3_reg_737;
wire   [11:0] i_V_fu_381_p2;
reg   [11:0] i_V_reg_745;
wire   [0:0] not4_fu_391_p2;
reg   [0:0] not4_reg_750;
wire   [0:0] exitcond1_fu_376_p2;
wire   [0:0] not5_fu_396_p2;
reg   [0:0] not5_reg_755;
wire   [31:0] bottom_6_fu_401_p1;
reg   [31:0] bottom_6_reg_760;
wire   [0:0] sel_tmp3_fu_405_p2;
reg   [0:0] sel_tmp3_reg_767;
wire   [0:0] exitcond_fu_411_p2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_772_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_772_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_772_pp0_it3;
wire   [11:0] j_V_fu_416_p2;
reg   [11:0] j_V_reg_776;
wire   [0:0] not9_fu_426_p2;
reg   [0:0] not9_reg_781;
reg   [0:0] ap_reg_ppstg_not9_reg_781_pp0_it1;
reg   [0:0] ap_reg_ppstg_not9_reg_781_pp0_it2;
wire   [0:0] or_cond1_fu_436_p2;
reg   [0:0] or_cond1_reg_787;
reg   [0:0] ap_reg_ppstg_or_cond1_reg_787_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond1_reg_787_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond1_reg_787_pp0_it3;
reg   [7:0] tmp_16_reg_791;
reg   [7:0] ap_reg_ppstg_tmp_16_reg_791_pp0_it2;
reg   [7:0] ap_reg_ppstg_tmp_16_reg_791_pp0_it3;
reg   [7:0] ap_reg_ppstg_tmp_16_reg_791_pp0_it4;
wire   [0:0] or_cond_fu_452_p2;
reg   [0:0] or_cond_reg_797;
reg   [0:0] ap_reg_ppstg_or_cond_reg_797_pp0_it3;
wire   [0:0] sel_tmp1_fu_464_p2;
reg   [0:0] sel_tmp1_reg_806;
wire   [31:0] right_6_fu_488_p1;
reg   [31:0] right_6_reg_811;
wire   [0:0] sel_tmp9_demorgan_fu_506_p2;
reg   [0:0] sel_tmp9_demorgan_reg_817;
wire   [0:0] sel_tmp2_fu_510_p2;
reg   [0:0] sel_tmp2_reg_823;
wire   [0:0] sel_tmp4_fu_514_p2;
reg   [0:0] sel_tmp4_reg_828;
wire   [31:0] bottom_1_fu_534_p3;
reg   [31:0] bottom_1_reg_834;
wire   [31:0] right_1_fu_557_p3;
reg   [31:0] right_1_reg_839;
reg   [11:0] t_V_5_reg_215;
reg   [11:0] ap_reg_phibuf_t_V_5_reg_215;
reg   [1:0] ap_NS_fsm;
reg   [11:0] t_V_phi_fu_231_p4;
wire   [63:0] tmp_11_fu_265_p5;
wire   [0:0] tmp_s_fu_244_p2;
wire   [31:0] tmp_48_i_cast_fu_260_p1;
wire   [63:0] tmp_13_fu_303_p5;
wire   [0:0] tmp_3_fu_282_p2;
wire   [31:0] tmp_51_i_cast_fu_298_p1;
wire   [31:0] top_1_fu_621_p3;
wire   [31:0] left_4_fu_660_p3;
reg   [31:0] right_fu_88;
reg   [31:0] left_1_fu_92;
wire   [31:0] left_fu_320_p1;
reg   [31:0] bottom_fu_96;
reg   [31:0] top_2_fu_100;
wire   [31:0] top_fu_316_p1;
wire   [7:0] tmp_fu_240_p1;
wire   [12:0] tmp_47_i_cast_fu_250_p1;
wire   [12:0] tmp_48_i_fu_254_p2;
wire   [7:0] tmp_12_fu_278_p1;
wire   [12:0] tmp_50_i_cast_fu_288_p1;
wire   [12:0] tmp_51_i_fu_292_p2;
wire   [12:0] retval_i_cast_fu_324_p1;
wire   [12:0] retval_i5_cast_fu_334_p1;
wire   [12:0] tmp_45_cast_fu_387_p1;
wire   [12:0] tmp_47_cast_fu_422_p1;
wire   [0:0] not6_fu_431_p2;
wire   [0:0] p_not_fu_441_p2;
wire   [0:0] not_fu_446_p2;
wire   [0:0] sel_tmp1_demorgan_fu_458_p2;
wire   [0:0] tmp_5_fu_476_p2;
wire   [0:0] tmp_7_fu_492_p2;
wire   [31:0] bottom_3_fu_481_p3;
wire   [31:0] bottom_4_fu_519_p3;
wire   [31:0] bottom_5_fu_526_p3;
wire   [31:0] right_3_fu_498_p3;
wire   [31:0] right_4_fu_542_p3;
wire   [31:0] right_5_fu_549_p3;
wire   [0:0] tmp_6_fu_581_p2;
wire   [11:0] tmp_15_fu_586_p1;
wire   [11:0] top_4_fu_590_p3;
wire   [31:0] top_5_cast_fu_598_p1;
wire   [31:0] sel_tmp6_fu_607_p3;
wire   [31:0] sel_tmp_fu_614_p3;
wire   [0:0] tmp_8_fu_602_p2;
wire   [0:0] tmp2_fu_629_p2;
wire   [0:0] sel_tmp8_fu_634_p2;
wire   [31:0] left_3_fu_639_p3;
wire   [31:0] left_5_fu_646_p3;
wire   [31:0] left_6_fu_653_p3;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 2'b00;
parameter    ap_ST_st2_fsm_1 = 2'b1;
parameter    ap_ST_pp0_stg0_fsm_2 = 2'b10;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv13_1FFF = 13'b1111111111111;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv64_7 = 64'b111;
parameter    ap_const_lv13_1F33 = 13'b1111100110011;
parameter    ap_const_lv13_1FC0 = 13'b1111111000000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv12_CE = 12'b11001110;
parameter    ap_true = 1'b1;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_376_p2))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_lv1_0 == exitcond_fu_411_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_376_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == exitcond_fu_411_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_376_p2)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_lv1_0 == exitcond_fu_411_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_376_p2))) begin
            ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_376_p2))) begin
            ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_376_p2))) begin
            ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_376_p2))) begin
            ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it2))) begin
        bottom_fu_96 <= bottom_1_fu_534_p3;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_106)) begin
        bottom_fu_96 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it3))) begin
        left_1_fu_92 <= left_4_fu_660_p3;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_106)) begin
        left_1_fu_92 <= left_fu_320_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond1_reg_787_pp0_it3))) begin
        p_bottom <= bottom_1_reg_834;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_106 & ~(ap_const_lv1_0 == tmp_s_fu_244_p2))) begin
        p_bottom <= tmp_48_i_cast_fu_260_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond1_reg_787_pp0_it3))) begin
        p_right <= right_1_reg_839;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_106 & ~(ap_const_lv1_0 == tmp_3_fu_282_p2))) begin
        p_right <= tmp_51_i_cast_fu_298_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it2))) begin
        right_fu_88 <= right_1_fu_557_p3;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_106)) begin
        right_fu_88 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_lv1_0 == exitcond_fu_411_p2) & (ap_ST_st2_fsm_1 == ap_NS_fsm))) begin
        t_V_5_reg_215 <= i_V_reg_745;
    end else if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & (ap_ST_st2_fsm_1 == ap_NS_fsm))) begin
        t_V_5_reg_215 <= ap_reg_phibuf_t_V_5_reg_215;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_106)) begin
        t_V_5_reg_215 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_376_p2))) begin
        t_V_reg_227 <= ap_const_lv12_0;
    end else if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_772 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        t_V_reg_227 <= j_V_reg_776;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it3))) begin
        top_2_fu_100 <= top_1_fu_621_p3;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_106)) begin
        top_2_fu_100 <= top_fu_316_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_lv1_0 == exitcond_fu_411_p2))) begin
        ap_reg_phibuf_t_V_5_reg_215 <= i_V_reg_745;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        ap_reg_ppstg_exitcond_reg_772_pp0_it1 <= exitcond_reg_772;
        ap_reg_ppstg_exitcond_reg_772_pp0_it2 <= ap_reg_ppstg_exitcond_reg_772_pp0_it1;
        ap_reg_ppstg_exitcond_reg_772_pp0_it3 <= ap_reg_ppstg_exitcond_reg_772_pp0_it2;
        ap_reg_ppstg_exitcond_reg_772_pp0_it4 <= ap_reg_ppstg_exitcond_reg_772_pp0_it3;
        ap_reg_ppstg_not9_reg_781_pp0_it1 <= not9_reg_781;
        ap_reg_ppstg_not9_reg_781_pp0_it2 <= ap_reg_ppstg_not9_reg_781_pp0_it1;
        ap_reg_ppstg_or_cond1_reg_787_pp0_it1 <= or_cond1_reg_787;
        ap_reg_ppstg_or_cond1_reg_787_pp0_it2 <= ap_reg_ppstg_or_cond1_reg_787_pp0_it1;
        ap_reg_ppstg_or_cond1_reg_787_pp0_it3 <= ap_reg_ppstg_or_cond1_reg_787_pp0_it2;
        ap_reg_ppstg_or_cond_reg_797_pp0_it3 <= or_cond_reg_797;
        ap_reg_ppstg_t_V_reg_227_pp0_it1 <= t_V_reg_227;
        ap_reg_ppstg_t_V_reg_227_pp0_it2 <= ap_reg_ppstg_t_V_reg_227_pp0_it1;
        ap_reg_ppstg_tmp_16_reg_791_pp0_it2 <= tmp_16_reg_791;
        ap_reg_ppstg_tmp_16_reg_791_pp0_it3 <= ap_reg_ppstg_tmp_16_reg_791_pp0_it2;
        ap_reg_ppstg_tmp_16_reg_791_pp0_it4 <= ap_reg_ppstg_tmp_16_reg_791_pp0_it3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it2))) begin
        bottom_1_reg_834 <= bottom_1_fu_534_p3;
        right_1_reg_839 <= right_1_fu_557_p3;
        right_6_reg_811[0] <= right_6_fu_488_p1[0];
right_6_reg_811[1] <= right_6_fu_488_p1[1];
right_6_reg_811[2] <= right_6_fu_488_p1[2];
right_6_reg_811[3] <= right_6_fu_488_p1[3];
right_6_reg_811[4] <= right_6_fu_488_p1[4];
right_6_reg_811[5] <= right_6_fu_488_p1[5];
right_6_reg_811[6] <= right_6_fu_488_p1[6];
right_6_reg_811[7] <= right_6_fu_488_p1[7];
right_6_reg_811[8] <= right_6_fu_488_p1[8];
right_6_reg_811[9] <= right_6_fu_488_p1[9];
right_6_reg_811[10] <= right_6_fu_488_p1[10];
right_6_reg_811[11] <= right_6_fu_488_p1[11];
        sel_tmp2_reg_823 <= sel_tmp2_fu_510_p2;
        sel_tmp4_reg_828 <= sel_tmp4_fu_514_p2;
        sel_tmp9_demorgan_reg_817 <= sel_tmp9_demorgan_fu_506_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_376_p2))) begin
        bottom_6_reg_760[0] <= bottom_6_fu_401_p1[0];
bottom_6_reg_760[1] <= bottom_6_fu_401_p1[1];
bottom_6_reg_760[2] <= bottom_6_fu_401_p1[2];
bottom_6_reg_760[3] <= bottom_6_fu_401_p1[3];
bottom_6_reg_760[4] <= bottom_6_fu_401_p1[4];
bottom_6_reg_760[5] <= bottom_6_fu_401_p1[5];
bottom_6_reg_760[6] <= bottom_6_fu_401_p1[6];
bottom_6_reg_760[7] <= bottom_6_fu_401_p1[7];
bottom_6_reg_760[8] <= bottom_6_fu_401_p1[8];
bottom_6_reg_760[9] <= bottom_6_fu_401_p1[9];
bottom_6_reg_760[10] <= bottom_6_fu_401_p1[10];
bottom_6_reg_760[11] <= bottom_6_fu_401_p1[11];
        not4_reg_750 <= not4_fu_391_p2;
        not5_reg_755 <= not5_fu_396_p2;
        sel_tmp3_reg_767 <= sel_tmp3_fu_405_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        exitcond_reg_772 <= exitcond_fu_411_p2;
        j_V_reg_776 <= j_V_fu_416_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_106 & ~(ap_const_lv1_0 == tmp_s_fu_244_p2))) begin
        guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns <= tmp_11_fu_265_p5;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_106 & ~(ap_const_lv1_0 == tmp_3_fu_282_p2))) begin
        guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns_1 <= tmp_13_fu_303_p5;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        i_V_reg_745 <= i_V_fu_381_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == exitcond_fu_411_p2))) begin
        not9_reg_781 <= not9_fu_426_p2;
        or_cond1_reg_787 <= or_cond1_fu_436_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_106)) begin
        op2_assign_3_reg_737 <= op2_assign_3_fu_350_p2;
        op2_assign_8_reg_722 <= op2_assign_8_fu_328_p2;
        op2_assign_9_reg_727 <= op2_assign_9_fu_338_p2;
        op2_assign_reg_732 <= op2_assign_fu_344_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it1))) begin
        or_cond_reg_797 <= or_cond_fu_452_p2;
        sel_tmp1_reg_806 <= sel_tmp1_fu_464_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond1_reg_787_pp0_it3))) begin
        p_left <= left_4_fu_660_p3;
        p_top <= top_1_fu_621_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_772 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        tmp_16_reg_791 <= src_data_stream_0_V_dout;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_CS_fsm or exitcond1_fu_376_p2)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_376_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond1_fu_376_p2)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_376_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// bb_bottom_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_67 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_772_pp0_it4 or ap_sig_bdd_93 or ap_reg_ppiten_pp0_it5)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        bb_bottom_V_write = ap_const_logic_1;
    end else begin
        bb_bottom_V_write = ap_const_logic_0;
    end
end

/// bb_left_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_67 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_772_pp0_it4 or ap_sig_bdd_93 or ap_reg_ppiten_pp0_it5)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        bb_left_V_write = ap_const_logic_1;
    end else begin
        bb_left_V_write = ap_const_logic_0;
    end
end

/// bb_right_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_67 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_772_pp0_it4 or ap_sig_bdd_93 or ap_reg_ppiten_pp0_it5)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        bb_right_V_write = ap_const_logic_1;
    end else begin
        bb_right_V_write = ap_const_logic_0;
    end
end

/// bb_top_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_67 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_772_pp0_it4 or ap_sig_bdd_93 or ap_reg_ppiten_pp0_it5)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        bb_top_V_write = ap_const_logic_1;
    end else begin
        bb_top_V_write = ap_const_logic_0;
    end
end

/// dst_data_stream_0_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_67 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_772_pp0_it4 or ap_sig_bdd_93 or ap_reg_ppiten_pp0_it5)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        dst_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        dst_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// src_data_stream_0_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_772 or ap_sig_bdd_67 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_93 or ap_reg_ppiten_pp0_it5)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_772 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        src_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        src_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// t_V_phi_fu_231_p4 assign process. ///
always @ (ap_CS_fsm or t_V_reg_227 or exitcond_reg_772 or ap_reg_ppiten_pp0_it1 or j_V_reg_776)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_772 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        t_V_phi_fu_231_p4 = j_V_reg_776;
    end else begin
        t_V_phi_fu_231_p4 = t_V_reg_227;
    end
end
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_67 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_93 or ap_reg_ppiten_pp0_it5 or ap_sig_bdd_106 or exitcond1_fu_376_p2 or exitcond_fu_411_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~ap_sig_bdd_106) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(ap_const_lv1_0 == exitcond1_fu_376_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        ap_ST_pp0_stg0_fsm_2 : 
            if ((~((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_lv1_0 == exitcond_fu_411_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_67 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_lv1_0 == exitcond_fu_411_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_106 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_106 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_67 assign process. ///
always @ (src_data_stream_0_V_empty_n or exitcond_reg_772)
begin
    ap_sig_bdd_67 = ((src_data_stream_0_V_empty_n == ap_const_logic_0) & (exitcond_reg_772 == ap_const_lv1_0));
end

/// ap_sig_bdd_93 assign process. ///
always @ (dst_data_stream_0_V_full_n or bb_top_V_full_n or bb_bottom_V_full_n or bb_left_V_full_n or bb_right_V_full_n or ap_reg_ppstg_exitcond_reg_772_pp0_it4)
begin
    ap_sig_bdd_93 = (((bb_top_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it4)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it4) & (bb_bottom_V_full_n == ap_const_logic_0)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it4) & (bb_left_V_full_n == ap_const_logic_0)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it4) & (bb_right_V_full_n == ap_const_logic_0)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_772_pp0_it4) & (dst_data_stream_0_V_full_n == ap_const_logic_0)));
end
assign bb_bottom_V_din = p_bottom;
assign bb_left_V_din = p_left;
assign bb_right_V_din = p_right;
assign bb_top_V_din = p_top;
assign bottom_1_fu_534_p3 = ((sel_tmp4_fu_514_p2)? bottom_fu_96: bottom_5_fu_526_p3);
assign bottom_3_fu_481_p3 = ((tmp_5_fu_476_p2)? bottom_6_reg_760: bottom_fu_96);
assign bottom_4_fu_519_p3 = ((or_cond_reg_797)? bottom_fu_96: bottom_3_fu_481_p3);
assign bottom_5_fu_526_p3 = ((sel_tmp9_demorgan_fu_506_p2)? bottom_4_fu_519_p3: bottom_fu_96);
assign bottom_6_fu_401_p1 = $unsigned(t_V_5_reg_215);
assign dst_data_stream_0_V_din = ap_reg_ppstg_tmp_16_reg_791_pp0_it4;
assign exitcond1_fu_376_p2 = (t_V_5_reg_215 == src_rows_V_read? 1'b1: 1'b0);
assign exitcond_fu_411_p2 = (t_V_phi_fu_231_p4 == src_cols_V_read? 1'b1: 1'b0);
assign i_V_fu_381_p2 = (t_V_5_reg_215 + ap_const_lv12_1);
assign j_V_fu_416_p2 = (t_V_phi_fu_231_p4 + ap_const_lv12_1);
assign left_3_fu_639_p3 = ((sel_tmp8_fu_634_p2)? right_6_reg_811: left_1_fu_92);
assign left_4_fu_660_p3 = ((sel_tmp4_reg_828)? left_1_fu_92: left_6_fu_653_p3);
assign left_5_fu_646_p3 = ((ap_reg_ppstg_or_cond_reg_797_pp0_it3)? left_1_fu_92: left_3_fu_639_p3);
assign left_6_fu_653_p3 = ((sel_tmp9_demorgan_reg_817)? left_5_fu_646_p3: left_1_fu_92);
assign left_fu_320_p1 = $unsigned(src_cols_V_read);
assign not4_fu_391_p2 = (tmp_45_cast_fu_387_p1 == op2_assign_8_reg_722? 1'b1: 1'b0);
assign not5_fu_396_p2 = (tmp_45_cast_fu_387_p1 < op2_assign_3_reg_737? 1'b1: 1'b0);
assign not6_fu_431_p2 = (tmp_47_cast_fu_422_p1 == op2_assign_9_reg_727? 1'b1: 1'b0);
assign not9_fu_426_p2 = (tmp_47_cast_fu_422_p1 < op2_assign_reg_732? 1'b1: 1'b0);
assign not_fu_446_p2 = (ap_reg_ppstg_t_V_reg_227_pp0_it1 < ap_const_lv12_CE? 1'b1: 1'b0);
assign op2_assign_3_fu_350_p2 = (retval_i_cast_fu_324_p1 + ap_const_lv13_1FC0);
assign op2_assign_8_fu_328_p2 = (retval_i_cast_fu_324_p1 + ap_const_lv13_1FFF);
assign op2_assign_9_fu_338_p2 = (retval_i5_cast_fu_334_p1 + ap_const_lv13_1FFF);
assign op2_assign_fu_344_p2 = (retval_i5_cast_fu_334_p1 + ap_const_lv13_1F33);
assign or_cond1_fu_436_p2 = (not4_reg_750 & not6_fu_431_p2);
assign or_cond_fu_452_p2 = (p_not_fu_441_p2 | not_fu_446_p2);
assign p_not_fu_441_p2 = (tmp_16_reg_791 != ap_const_lv8_0? 1'b1: 1'b0);
assign retval_i5_cast_fu_334_p1 = $unsigned(src_cols_V_read);
assign retval_i_cast_fu_324_p1 = $unsigned(src_rows_V_read);
assign right_1_fu_557_p3 = ((sel_tmp4_fu_514_p2)? right_fu_88: right_5_fu_549_p3);
assign right_3_fu_498_p3 = ((tmp_7_fu_492_p2)? right_6_fu_488_p1: right_fu_88);
assign right_4_fu_542_p3 = ((or_cond_reg_797)? right_fu_88: right_3_fu_498_p3);
assign right_5_fu_549_p3 = ((sel_tmp9_demorgan_fu_506_p2)? right_4_fu_542_p3: right_fu_88);
assign right_6_fu_488_p1 = $unsigned(ap_reg_ppstg_t_V_reg_227_pp0_it2);
assign sel_tmp1_demorgan_fu_458_p2 = (p_not_fu_441_p2 | not_fu_446_p2);
assign sel_tmp1_fu_464_p2 = (sel_tmp1_demorgan_fu_458_p2 ^ ap_const_lv1_1);
assign sel_tmp2_fu_510_p2 = (ap_reg_ppstg_not9_reg_781_pp0_it2 & sel_tmp1_reg_806);
assign sel_tmp3_fu_405_p2 = (not5_fu_396_p2 ^ ap_const_lv1_1);
assign sel_tmp4_fu_514_p2 = (sel_tmp2_fu_510_p2 & sel_tmp3_reg_767);
assign sel_tmp6_fu_607_p3 = ((ap_reg_ppstg_or_cond_reg_797_pp0_it3)? top_2_fu_100: top_5_cast_fu_598_p1);
assign sel_tmp8_fu_634_p2 = (tmp2_fu_629_p2 & sel_tmp2_reg_823);
assign sel_tmp9_demorgan_fu_506_p2 = (or_cond_reg_797 | ap_reg_ppstg_not9_reg_781_pp0_it2);
assign sel_tmp_fu_614_p3 = ((sel_tmp9_demorgan_reg_817)? sel_tmp6_fu_607_p3: top_2_fu_100);
assign tmp2_fu_629_p2 = (not5_reg_755 & tmp_8_fu_602_p2);
assign tmp_11_fu_265_p5 = {{guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns[32'd63 : 32'd8]}, {ap_const_lv8_1}};
assign tmp_12_fu_278_p1 = guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns_1[7:0];
assign tmp_13_fu_303_p5 = {{guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns_1[32'd63 : 32'd8]}, {ap_const_lv8_1}};
assign tmp_15_fu_586_p1 = top_2_fu_100[11:0];
assign tmp_3_fu_282_p2 = (tmp_12_fu_278_p1 == ap_const_lv8_0? 1'b1: 1'b0);
assign tmp_45_cast_fu_387_p1 = $unsigned(t_V_5_reg_215);
assign tmp_47_cast_fu_422_p1 = $unsigned(t_V_phi_fu_231_p4);
assign tmp_47_i_cast_fu_250_p1 = $unsigned(src_rows_V_read);
assign tmp_48_i_cast_fu_260_p1 = $signed(tmp_48_i_fu_254_p2);
assign tmp_48_i_fu_254_p2 = (tmp_47_i_cast_fu_250_p1 + ap_const_lv13_1FFF);
assign tmp_50_i_cast_fu_288_p1 = $unsigned(src_cols_V_read);
assign tmp_51_i_cast_fu_298_p1 = $signed(tmp_51_i_fu_292_p2);
assign tmp_51_i_fu_292_p2 = (tmp_50_i_cast_fu_288_p1 + ap_const_lv13_1FFF);
assign tmp_5_fu_476_p2 = (bottom_6_reg_760 > bottom_fu_96? 1'b1: 1'b0);
assign tmp_6_fu_581_p2 = (bottom_6_reg_760 < top_2_fu_100? 1'b1: 1'b0);
assign tmp_7_fu_492_p2 = (right_6_fu_488_p1 > right_fu_88? 1'b1: 1'b0);
assign tmp_8_fu_602_p2 = (right_6_reg_811 < left_1_fu_92? 1'b1: 1'b0);
assign tmp_fu_240_p1 = guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns[7:0];
assign tmp_s_fu_244_p2 = (tmp_fu_240_p1 == ap_const_lv8_0? 1'b1: 1'b0);
assign top_1_fu_621_p3 = ((sel_tmp4_reg_828)? top_2_fu_100: sel_tmp_fu_614_p3);
assign top_4_fu_590_p3 = ((tmp_6_fu_581_p2)? t_V_5_reg_215: tmp_15_fu_586_p1);
assign top_5_cast_fu_598_p1 = $unsigned(top_4_fu_590_p3);
assign top_fu_316_p1 = $unsigned(src_rows_V_read);
always @ (posedge ap_clk)
begin
    bottom_6_reg_760[31:12] <= 20'b00000000000000000000;
    right_6_reg_811[31:12] <= 20'b00000000000000000000;
end



endmodule //bounding_box

