-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2013.2
-- Copyright (C) 2013 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity draw is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    src_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    src_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    src_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    src_data_stream_0_V_empty_n : IN STD_LOGIC;
    src_data_stream_0_V_read : OUT STD_LOGIC;
    dst_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_data_stream_0_V_full_n : IN STD_LOGIC;
    dst_data_stream_0_V_write : OUT STD_LOGIC;
    dst_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_data_stream_1_V_full_n : IN STD_LOGIC;
    dst_data_stream_1_V_write : OUT STD_LOGIC;
    dst_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_data_stream_2_V_full_n : IN STD_LOGIC;
    dst_data_stream_2_V_write : OUT STD_LOGIC;
    bb_top_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    bb_top_V_empty_n : IN STD_LOGIC;
    bb_top_V_read : OUT STD_LOGIC;
    bb_bottom_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    bb_bottom_V_empty_n : IN STD_LOGIC;
    bb_bottom_V_read : OUT STD_LOGIC;
    bb_left_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    bb_left_V_empty_n : IN STD_LOGIC;
    bb_left_V_read : OUT STD_LOGIC;
    bb_right_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    bb_right_V_empty_n : IN STD_LOGIC;
    bb_right_V_read : OUT STD_LOGIC;
    err_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    err_V_empty_n : IN STD_LOGIC;
    err_V_read : OUT STD_LOGIC;
    val_V_V_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    val_V_V_empty_n : IN STD_LOGIC;
    val_V_V_read : OUT STD_LOGIC );
end;


architecture behav of draw is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_pp0_stg0_fsm_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_18F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001111";
    constant ap_const_lv32_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110010000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_64 : STD_LOGIC_VECTOR (7 downto 0) := "01100100";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal t_V_reg_205 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_bdd_73 : BOOLEAN;
    signal i_V_fu_232_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal i_V_reg_582 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_s_fu_238_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_reg_587 : STD_LOGIC_VECTOR (31 downto 0);
    signal exitcond4_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_reg_593 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC := '0';
    signal ap_sig_bdd_114 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it2 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it3 : STD_LOGIC := '0';
    signal ap_reg_ppstg_exitcond_reg_593_pp0_it3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_bdd_132 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it4 : STD_LOGIC := '0';
    signal ap_reg_ppstg_exitcond_reg_593_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_exitcond_reg_593_pp0_it2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_V_fu_247_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal j_V_reg_597 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_3_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_611 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_3_reg_611_pp0_it2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_3_reg_611_pp0_it3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_618 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_reg_623 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_reg_628 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond7_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond7_reg_634 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_639 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_645 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_demorgan_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_demorgan_reg_650 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_reg_656 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_cast_fu_405_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp9_cast_reg_663 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_fu_413_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_reg_668 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_reg_675 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_429_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp14_reg_682 : STD_LOGIC_VECTOR (7 downto 0);
    signal t_V_7_reg_194 : STD_LOGIC_VECTOR (11 downto 0);
    signal t_V_phi_fu_209_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_V_fiforead_fu_136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_out_val_0_1_fu_497_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixel_out_val_1_1_fu_471_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixel_out_val_2_1_fu_519_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_cond_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond5_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_out_val_2_fu_92 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixel_out_val_0_fu_96 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixel_out_val_1_fu_100 : STD_LOGIC_VECTOR (7 downto 0);
    signal state_loc_2_fu_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal extLd_fu_218_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_not_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_302_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_demorgan_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_demorgan_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_459_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_452_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp3_fu_446_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp6_fu_463_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp13_fu_489_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3_temp: signed (1-1 downto 0);
    signal sel_tmp11_fu_479_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp13_fu_489_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp15_fu_505_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp16_fu_511_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_bdd_482 : BOOLEAN;
    signal ap_sig_bdd_414 : BOOLEAN;


begin



    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_done_reg assign process. --
    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_ST_st2_fsm_1 = ap_CS_fsm) and not((exitcond4_fu_227_p2 = ap_const_lv1_0)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it0 assign process. --
    ap_reg_ppiten_pp0_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = exitcond_fu_242_p2)))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
                elsif (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond4_fu_227_p2 = ap_const_lv1_0))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it1 assign process. --
    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = exitcond_fu_242_p2))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
                elsif ((((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond4_fu_227_p2 = ap_const_lv1_0)) or ((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = exitcond_fu_242_p2))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it2 assign process. --
    ap_reg_ppiten_pp0_it2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
                    ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
                elsif (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond4_fu_227_p2 = ap_const_lv1_0))) then 
                    ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it3 assign process. --
    ap_reg_ppiten_pp0_it3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
                    ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
                elsif (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond4_fu_227_p2 = ap_const_lv1_0))) then 
                    ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it4 assign process. --
    ap_reg_ppiten_pp0_it4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
                    ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
                elsif (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond4_fu_227_p2 = ap_const_lv1_0))) then 
                    ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- state assign process. --
    state_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (ap_sig_bdd_414) then
                if (ap_sig_bdd_482) then 
                    state(0) <= '0';
                elsif ((ap_const_lv1_0 = or_cond_fu_268_p2)) then 
                    state(0) <= '1';
                end if;
            end if; 
        end if;
    end process;

    -- state_loc_2_fu_104 assign process. --
    state_loc_2_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_reg_593) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = tmp_V_fiforead_fu_136_p2)) and not((ap_const_lv1_0 = or_cond_fu_268_p2)) and not((ap_const_lv1_0 = or_cond5_fu_291_p2)))) then 
                state_loc_2_fu_104(0) <= '0';
            elsif (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_reg_593) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = tmp_V_fiforead_fu_136_p2)) and (ap_const_lv1_0 = or_cond_fu_268_p2))) then 
                state_loc_2_fu_104(0) <= '1';
            elsif (((ap_ST_st1_fsm_0 = ap_CS_fsm) and not(ap_sig_bdd_73))) then 
                state_loc_2_fu_104(0) <= extLd_fu_218_p1(0);
            end if; 
        end if;
    end process;

    -- t_V_7_reg_194 assign process. --
    t_V_7_reg_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = exitcond_fu_242_p2)))) then 
                t_V_7_reg_194 <= i_V_reg_582;
            elsif (((ap_ST_st1_fsm_0 = ap_CS_fsm) and not(ap_sig_bdd_73))) then 
                t_V_7_reg_194 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;

    -- t_V_reg_205 assign process. --
    t_V_reg_205_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_reg_593) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
                t_V_reg_205 <= j_V_reg_597;
            elsif (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond4_fu_227_p2 = ap_const_lv1_0))) then 
                t_V_reg_205 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then
                ap_reg_ppstg_exitcond_reg_593_pp0_it1 <= exitcond_reg_593;
                ap_reg_ppstg_exitcond_reg_593_pp0_it2 <= ap_reg_ppstg_exitcond_reg_593_pp0_it1;
                ap_reg_ppstg_exitcond_reg_593_pp0_it3 <= ap_reg_ppstg_exitcond_reg_593_pp0_it2;
                ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3 <= sel_tmp4_reg_656;
                ap_reg_ppstg_tmp_3_reg_611_pp0_it2 <= tmp_3_reg_611;
                ap_reg_ppstg_tmp_3_reg_611_pp0_it3 <= ap_reg_ppstg_tmp_3_reg_611_pp0_it2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then
                exitcond_reg_593 <= exitcond_fu_242_p2;
                j_V_reg_597 <= j_V_fu_247_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_ST_st2_fsm_1 = ap_CS_fsm)) then
                i_V_reg_582 <= i_V_fu_232_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_593_pp0_it1))) then
                or_cond7_reg_634 <= or_cond7_fu_343_p2;
                sel_tmp4_reg_656 <= sel_tmp4_fu_375_p2;
                sel_tmp5_demorgan_reg_650 <= sel_tmp5_demorgan_fu_364_p2;
                tmp_16_reg_639 <= tmp_16_fu_347_p2;
                tmp_17_reg_645 <= tmp_17_fu_353_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_593_pp0_it3) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then
                pixel_out_val_0_fu_96 <= pixel_out_val_0_1_fu_497_p3;
                pixel_out_val_1_fu_100 <= pixel_out_val_1_1_fu_471_p3;
                pixel_out_val_2_fu_92 <= pixel_out_val_2_1_fu_519_p3;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_593_pp0_it2))) then
                sel_tmp10_reg_675 <= sel_tmp10_fu_424_p2;
                sel_tmp14_reg_682(0) <= sel_tmp14_fu_429_p3(0);
    sel_tmp14_reg_682(1) <= sel_tmp14_fu_429_p3(1);
    sel_tmp14_reg_682(3) <= sel_tmp14_fu_429_p3(3);
    sel_tmp14_reg_682(4) <= sel_tmp14_fu_429_p3(4);
    sel_tmp14_reg_682(7) <= sel_tmp14_fu_429_p3(7);
                sel_tmp9_cast_reg_663(2) <= sel_tmp9_cast_fu_405_p3(2);
    sel_tmp9_cast_reg_663(5) <= sel_tmp9_cast_fu_405_p3(5);
    sel_tmp9_cast_reg_663(6) <= sel_tmp9_cast_fu_405_p3(6);
                tmp_19_reg_668 <= tmp_19_fu_413_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_reg_593) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then
                tmp2_reg_623 <= tmp2_fu_328_p2;
                tmp_15_reg_628 <= tmp_15_fu_334_p2;
                tmp_3_reg_611 <= tmp_3_fu_306_p2;
                tmp_4_reg_618 <= tmp_4_fu_312_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond4_fu_227_p2 = ap_const_lv1_0))) then
                tmp_s_reg_587(0) <= tmp_s_fu_238_p1(0);
    tmp_s_reg_587(1) <= tmp_s_fu_238_p1(1);
    tmp_s_reg_587(2) <= tmp_s_fu_238_p1(2);
    tmp_s_reg_587(3) <= tmp_s_fu_238_p1(3);
    tmp_s_reg_587(4) <= tmp_s_fu_238_p1(4);
    tmp_s_reg_587(5) <= tmp_s_fu_238_p1(5);
    tmp_s_reg_587(6) <= tmp_s_fu_238_p1(6);
    tmp_s_reg_587(7) <= tmp_s_fu_238_p1(7);
    tmp_s_reg_587(8) <= tmp_s_fu_238_p1(8);
    tmp_s_reg_587(9) <= tmp_s_fu_238_p1(9);
    tmp_s_reg_587(10) <= tmp_s_fu_238_p1(10);
    tmp_s_reg_587(11) <= tmp_s_fu_238_p1(11);
            end if;
        end if;
    end process;
    state(1) <= '0';
    tmp_s_reg_587(31 downto 12) <= "00000000000000000000";
    sel_tmp9_cast_reg_663(1 downto 0) <= "00";
    sel_tmp9_cast_reg_663(4 downto 3) <= "00";
    sel_tmp9_cast_reg_663(7) <= '0';
    sel_tmp14_reg_682(2) <= '1';
    sel_tmp14_reg_682(6 downto 5) <= "11";
    state_loc_2_fu_104(31 downto 1) <= "0000000000000000000000000000000";

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_CS_fsm , ap_sig_bdd_73 , exitcond4_fu_227_p2 , exitcond_fu_242_p2 , ap_reg_ppiten_pp0_it0 , ap_sig_bdd_114 , ap_reg_ppiten_pp0_it1 , ap_reg_ppiten_pp0_it3 , ap_sig_bdd_132 , ap_reg_ppiten_pp0_it4)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not(ap_sig_bdd_73)) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if (not((exitcond4_fu_227_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                end if;
            when ap_ST_pp0_stg0_fsm_2 => 
                if ((not(((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it3)))) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = exitcond_fu_242_p2)) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                elsif ((((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it3))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = exitcond_fu_242_p2)) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;

    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm, exitcond4_fu_227_p2)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or ((ap_ST_st2_fsm_1 = ap_CS_fsm) and not((exitcond4_fu_227_p2 = ap_const_lv1_0))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_CS_fsm)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_ST_st1_fsm_0 = ap_CS_fsm))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(ap_CS_fsm, exitcond4_fu_227_p2)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and not((exitcond4_fu_227_p2 = ap_const_lv1_0)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_bdd_114 assign process. --
    ap_sig_bdd_114_assign_proc : process(src_data_stream_0_V_empty_n, bb_top_V_empty_n, bb_bottom_V_empty_n, bb_left_V_empty_n, bb_right_V_empty_n, err_V_empty_n, val_V_V_empty_n, exitcond_reg_593)
    begin
                ap_sig_bdd_114 <= (((src_data_stream_0_V_empty_n = ap_const_logic_0) and (ap_const_lv1_0 = exitcond_reg_593)) or ((ap_const_lv1_0 = exitcond_reg_593) and (err_V_empty_n = ap_const_logic_0)) or ((ap_const_lv1_0 = exitcond_reg_593) and (val_V_V_empty_n = ap_const_logic_0)) or ((ap_const_lv1_0 = exitcond_reg_593) and (bb_top_V_empty_n = ap_const_logic_0)) or ((ap_const_lv1_0 = exitcond_reg_593) and (bb_bottom_V_empty_n = ap_const_logic_0)) or ((ap_const_lv1_0 = exitcond_reg_593) and (bb_left_V_empty_n = ap_const_logic_0)) or ((ap_const_lv1_0 = exitcond_reg_593) and (bb_right_V_empty_n = ap_const_logic_0)));
    end process;


    -- ap_sig_bdd_132 assign process. --
    ap_sig_bdd_132_assign_proc : process(dst_data_stream_0_V_full_n, dst_data_stream_1_V_full_n, dst_data_stream_2_V_full_n, ap_reg_ppstg_exitcond_reg_593_pp0_it3)
    begin
                ap_sig_bdd_132 <= (((dst_data_stream_0_V_full_n = ap_const_logic_0) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_593_pp0_it3)) or ((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_593_pp0_it3) and (dst_data_stream_1_V_full_n = ap_const_logic_0)) or ((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_593_pp0_it3) and (dst_data_stream_2_V_full_n = ap_const_logic_0)));
    end process;


    -- ap_sig_bdd_414 assign process. --
    ap_sig_bdd_414_assign_proc : process(ap_CS_fsm, exitcond_reg_593, ap_sig_bdd_114, ap_reg_ppiten_pp0_it1, ap_sig_bdd_132, ap_reg_ppiten_pp0_it4, tmp_V_fiforead_fu_136_p2)
    begin
                ap_sig_bdd_414 <= ((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_reg_593) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = tmp_V_fiforead_fu_136_p2)));
    end process;


    -- ap_sig_bdd_482 assign process. --
    ap_sig_bdd_482_assign_proc : process(or_cond_fu_268_p2, or_cond5_fu_291_p2)
    begin
                ap_sig_bdd_482 <= (not((ap_const_lv1_0 = or_cond_fu_268_p2)) and not((ap_const_lv1_0 = or_cond5_fu_291_p2)));
    end process;


    -- ap_sig_bdd_73 assign process. --
    ap_sig_bdd_73_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_sig_bdd_73 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    -- bb_bottom_V_read assign process. --
    bb_bottom_V_read_assign_proc : process(ap_CS_fsm, exitcond_reg_593, ap_sig_bdd_114, ap_reg_ppiten_pp0_it1, ap_sig_bdd_132, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_reg_593) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            bb_bottom_V_read <= ap_const_logic_1;
        else 
            bb_bottom_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- bb_left_V_read assign process. --
    bb_left_V_read_assign_proc : process(ap_CS_fsm, exitcond_reg_593, ap_sig_bdd_114, ap_reg_ppiten_pp0_it1, ap_sig_bdd_132, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_reg_593) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            bb_left_V_read <= ap_const_logic_1;
        else 
            bb_left_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- bb_right_V_read assign process. --
    bb_right_V_read_assign_proc : process(ap_CS_fsm, exitcond_reg_593, ap_sig_bdd_114, ap_reg_ppiten_pp0_it1, ap_sig_bdd_132, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_reg_593) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            bb_right_V_read <= ap_const_logic_1;
        else 
            bb_right_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- bb_top_V_read assign process. --
    bb_top_V_read_assign_proc : process(ap_CS_fsm, exitcond_reg_593, ap_sig_bdd_114, ap_reg_ppiten_pp0_it1, ap_sig_bdd_132, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_reg_593) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            bb_top_V_read <= ap_const_logic_1;
        else 
            bb_top_V_read <= ap_const_logic_0;
        end if; 
    end process;

    dst_data_stream_0_V_din <= 
        ap_const_lv8_0 when (sel_tmp10_reg_675(0) = '1') else 
        sel_tmp13_fu_489_p3;

    -- dst_data_stream_0_V_write assign process. --
    dst_data_stream_0_V_write_assign_proc : process(ap_CS_fsm, ap_sig_bdd_114, ap_reg_ppiten_pp0_it1, ap_reg_ppstg_exitcond_reg_593_pp0_it3, ap_sig_bdd_132, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_593_pp0_it3) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            dst_data_stream_0_V_write <= ap_const_logic_1;
        else 
            dst_data_stream_0_V_write <= ap_const_logic_0;
        end if; 
    end process;

    dst_data_stream_1_V_din <= 
        ap_const_lv8_FF when (sel_tmp10_reg_675(0) = '1') else 
        sel_tmp6_fu_463_p3;

    -- dst_data_stream_1_V_write assign process. --
    dst_data_stream_1_V_write_assign_proc : process(ap_CS_fsm, ap_sig_bdd_114, ap_reg_ppiten_pp0_it1, ap_reg_ppstg_exitcond_reg_593_pp0_it3, ap_sig_bdd_132, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_593_pp0_it3) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            dst_data_stream_1_V_write <= ap_const_logic_1;
        else 
            dst_data_stream_1_V_write <= ap_const_logic_0;
        end if; 
    end process;

    dst_data_stream_2_V_din <= 
        ap_const_lv8_0 when (sel_tmp10_reg_675(0) = '1') else 
        sel_tmp16_fu_511_p3;

    -- dst_data_stream_2_V_write assign process. --
    dst_data_stream_2_V_write_assign_proc : process(ap_CS_fsm, ap_sig_bdd_114, ap_reg_ppiten_pp0_it1, ap_reg_ppstg_exitcond_reg_593_pp0_it3, ap_sig_bdd_132, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_593_pp0_it3) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            dst_data_stream_2_V_write <= ap_const_logic_1;
        else 
            dst_data_stream_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    -- err_V_read assign process. --
    err_V_read_assign_proc : process(ap_CS_fsm, exitcond_reg_593, ap_sig_bdd_114, ap_reg_ppiten_pp0_it1, ap_sig_bdd_132, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_reg_593) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            err_V_read <= ap_const_logic_1;
        else 
            err_V_read <= ap_const_logic_0;
        end if; 
    end process;

    exitcond4_fu_227_p2 <= "1" when (t_V_7_reg_194 = src_rows_V_read) else "0";
    exitcond_fu_242_p2 <= "1" when (t_V_phi_fu_209_p4 = src_cols_V_read) else "0";
    extLd_fu_218_p1 <= std_logic_vector(resize(unsigned(state),32));
    i_V_fu_232_p2 <= std_logic_vector(unsigned(t_V_7_reg_194) + unsigned(ap_const_lv12_1));
    j_V_fu_247_p2 <= std_logic_vector(unsigned(t_V_phi_fu_209_p4) + unsigned(ap_const_lv12_1));
    or_cond5_fu_291_p2 <= (tmp_8_fu_279_p2 and tmp_1_fu_285_p2);
    or_cond7_fu_343_p2 <= (tmp2_reg_623 or tmp_4_reg_618);
    or_cond_fu_268_p2 <= (p_not_fu_256_p2 or tmp_7_fu_262_p2);
    p_not_fu_256_p2 <= "0" when (state_loc_2_fu_104 = ap_const_lv32_0) else "1";
    pixel_out_val_0_1_fu_497_p3 <= 
        ap_const_lv8_0 when (sel_tmp10_reg_675(0) = '1') else 
        sel_tmp13_fu_489_p3;
    pixel_out_val_1_1_fu_471_p3 <= 
        ap_const_lv8_FF when (sel_tmp10_reg_675(0) = '1') else 
        sel_tmp6_fu_463_p3;
    pixel_out_val_2_1_fu_519_p3 <= 
        ap_const_lv8_0 when (sel_tmp10_reg_675(0) = '1') else 
        sel_tmp16_fu_511_p3;
    sel_tmp10_fu_424_p2 <= (tmp_16_reg_639 and sel_tmp9_fu_419_p2);
    sel_tmp11_fu_479_p3 <= 
        ap_const_lv8_0 when (tmp_19_reg_668(0) = '1') else 
        pixel_out_val_0_fu_96;
    
    ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3_temp <= signed(ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3);
    sel_tmp13_fu_489_p1 <= std_logic_vector(resize(ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3_temp,8));

    sel_tmp13_fu_489_p3 <= 
        sel_tmp13_fu_489_p1 when (tmp_20_fu_459_p2(0) = '1') else 
        sel_tmp11_fu_479_p3;
    sel_tmp14_fu_429_p3 <= 
        ap_const_lv8_64 when (sel_tmp2_fu_400_p2(0) = '1') else 
        ap_const_lv8_FF;
    sel_tmp15_fu_505_p3 <= 
        sel_tmp14_reg_682 when (tmp_19_reg_668(0) = '1') else 
        pixel_out_val_2_fu_92;
    sel_tmp16_fu_511_p3 <= 
        sel_tmp5_fu_452_p3 when (tmp_20_fu_459_p2(0) = '1') else 
        sel_tmp15_fu_505_p3;
    sel_tmp1_fu_395_p2 <= (ap_reg_ppstg_tmp_3_reg_611_pp0_it2 xor ap_const_lv1_1);
    sel_tmp2_fu_400_p2 <= (or_cond7_reg_634 and sel_tmp1_fu_395_p2);
    sel_tmp3_demorgan_fu_359_p2 <= (tmp_3_reg_611 or or_cond7_fu_343_p2);
    sel_tmp3_fu_446_p3 <= 
        sel_tmp9_cast_reg_663 when (tmp_19_reg_668(0) = '1') else 
        pixel_out_val_1_fu_100;
    sel_tmp4_fu_375_p2 <= (tmp_15_reg_628 and sel_tmp_fu_369_p2);
    sel_tmp5_demorgan_fu_364_p2 <= (sel_tmp3_demorgan_fu_359_p2 or tmp_15_reg_628);
    sel_tmp5_fu_452_p3 <= 
        ap_const_lv8_FF when (ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3(0) = '1') else 
        ap_const_lv8_64;
    sel_tmp6_fu_463_p3 <= 
        sel_tmp5_fu_452_p3 when (tmp_20_fu_459_p2(0) = '1') else 
        sel_tmp3_fu_446_p3;
    sel_tmp7_demorgan_fu_380_p2 <= (sel_tmp5_demorgan_reg_650 or tmp_16_reg_639);
    sel_tmp7_fu_384_p2 <= (sel_tmp7_demorgan_fu_380_p2 xor ap_const_lv1_1);
    sel_tmp8_fu_390_p2 <= (tmp_17_reg_645 and sel_tmp7_fu_384_p2);
    sel_tmp9_cast_fu_405_p3 <= 
        ap_const_lv8_64 when (sel_tmp2_fu_400_p2(0) = '1') else 
        ap_const_lv8_0;
    sel_tmp9_fu_419_p2 <= (sel_tmp5_demorgan_reg_650 xor ap_const_lv1_1);
    sel_tmp_fu_369_p2 <= (sel_tmp3_demorgan_fu_359_p2 xor ap_const_lv1_1);

    -- src_data_stream_0_V_read assign process. --
    src_data_stream_0_V_read_assign_proc : process(ap_CS_fsm, exitcond_reg_593, ap_sig_bdd_114, ap_reg_ppiten_pp0_it1, ap_sig_bdd_132, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_reg_593) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            src_data_stream_0_V_read <= ap_const_logic_1;
        else 
            src_data_stream_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- t_V_phi_fu_209_p4 assign process. --
    t_V_phi_fu_209_p4_assign_proc : process(ap_CS_fsm, t_V_reg_205, exitcond_reg_593, ap_reg_ppiten_pp0_it1, j_V_reg_597)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_reg_593) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) then 
            t_V_phi_fu_209_p4 <= j_V_reg_597;
        else 
            t_V_phi_fu_209_p4 <= t_V_reg_205;
        end if; 
    end process;

    tmp2_fu_328_p2 <= (tmp_5_fu_318_p2 or tmp_6_fu_323_p2);
    tmp_15_fu_334_p2 <= "1" when (src_data_stream_0_V_dout = ap_const_lv8_FF) else "0";
    tmp_16_fu_347_p2 <= "1" when (state_loc_2_fu_104 = ap_const_lv32_1) else "0";
    tmp_17_fu_353_p2 <= "1" when (state_loc_2_fu_104 = ap_const_lv32_0) else "0";
    tmp_19_fu_413_p2 <= (sel_tmp2_fu_400_p2 or sel_tmp8_fu_390_p2);
    tmp_1_fu_285_p2 <= "1" when (unsigned(err_V_dout) > unsigned(ap_const_lv32_190)) else "0";
    tmp_20_fu_459_p2 <= (ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3 or ap_reg_ppstg_tmp_3_reg_611_pp0_it3);
    tmp_2_fu_302_p1 <= std_logic_vector(resize(unsigned(t_V_reg_205),32));
    tmp_3_fu_306_p2 <= "1" when (tmp_2_fu_302_p1 = bb_left_V_dout) else "0";
    tmp_4_fu_312_p2 <= "1" when (tmp_2_fu_302_p1 = bb_right_V_dout) else "0";
    tmp_5_fu_318_p2 <= "1" when (tmp_s_reg_587 = bb_top_V_dout) else "0";
    tmp_6_fu_323_p2 <= "1" when (tmp_s_reg_587 = bb_bottom_V_dout) else "0";
    tmp_7_fu_262_p2 <= "1" when (unsigned(err_V_dout) > unsigned(ap_const_lv32_18F)) else "0";
    tmp_8_fu_279_p2 <= "1" when (state_loc_2_fu_104 = ap_const_lv32_1) else "0";
    tmp_V_fiforead_fu_136_p2 <= val_V_V_dout;
    tmp_s_fu_238_p1 <= std_logic_vector(resize(unsigned(t_V_7_reg_194),32));

    -- val_V_V_read assign process. --
    val_V_V_read_assign_proc : process(ap_CS_fsm, exitcond_reg_593, ap_sig_bdd_114, ap_reg_ppiten_pp0_it1, ap_sig_bdd_132, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_reg_593) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_114 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_132 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            val_V_V_read <= ap_const_logic_1;
        else 
            val_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
