// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "bounding_box.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic bounding_box::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic bounding_box::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> bounding_box::ap_ST_st1_fsm_0 = "00";
const sc_lv<2> bounding_box::ap_ST_st2_fsm_1 = "1";
const sc_lv<2> bounding_box::ap_ST_pp0_stg0_fsm_2 = "10";
const sc_lv<64> bounding_box::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> bounding_box::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> bounding_box::ap_const_lv1_0 = "0";
const sc_lv<12> bounding_box::ap_const_lv12_0 = "000000000000";
const sc_lv<8> bounding_box::ap_const_lv8_0 = "00000000";
const sc_lv<13> bounding_box::ap_const_lv13_1FFF = "1111111111111";
const sc_lv<8> bounding_box::ap_const_lv8_1 = "1";
const sc_lv<64> bounding_box::ap_const_lv64_7 = "111";
const sc_lv<13> bounding_box::ap_const_lv13_1F33 = "1111100110011";
const sc_lv<13> bounding_box::ap_const_lv13_1FC0 = "1111111000000";
const sc_lv<12> bounding_box::ap_const_lv12_1 = "1";
const sc_lv<1> bounding_box::ap_const_lv1_1 = "1";
const sc_lv<12> bounding_box::ap_const_lv12_CE = "11001110";

bounding_box::bounding_box(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_376_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_376_p2 );

    SC_METHOD(thread_ap_sig_bdd_106);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_67);
    sensitive << ( src_data_stream_0_V_empty_n );
    sensitive << ( exitcond_reg_772 );

    SC_METHOD(thread_ap_sig_bdd_93);
    sensitive << ( dst_data_stream_0_V_full_n );
    sensitive << ( bb_top_V_full_n );
    sensitive << ( bb_bottom_V_full_n );
    sensitive << ( bb_left_V_full_n );
    sensitive << ( bb_right_V_full_n );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it4 );

    SC_METHOD(thread_bb_bottom_V_din);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_bottom );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it4 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_bb_bottom_V_write);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it4 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_bb_left_V_din);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_left );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it4 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_bb_left_V_write);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it4 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_bb_right_V_din);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_right );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it4 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_bb_right_V_write);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it4 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_bb_top_V_din);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_top );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it4 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_bb_top_V_write);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it4 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_bottom_1_fu_534_p3);
    sensitive << ( sel_tmp4_fu_514_p2 );
    sensitive << ( bottom_fu_96 );
    sensitive << ( bottom_5_fu_526_p3 );

    SC_METHOD(thread_bottom_3_fu_481_p3);
    sensitive << ( bottom_6_reg_760 );
    sensitive << ( bottom_fu_96 );
    sensitive << ( tmp_5_fu_476_p2 );

    SC_METHOD(thread_bottom_4_fu_519_p3);
    sensitive << ( or_cond_reg_797 );
    sensitive << ( bottom_fu_96 );
    sensitive << ( bottom_3_fu_481_p3 );

    SC_METHOD(thread_bottom_5_fu_526_p3);
    sensitive << ( sel_tmp9_demorgan_fu_506_p2 );
    sensitive << ( bottom_fu_96 );
    sensitive << ( bottom_4_fu_519_p3 );

    SC_METHOD(thread_bottom_6_fu_401_p1);
    sensitive << ( t_V_5_reg_215 );

    SC_METHOD(thread_dst_data_stream_0_V_din);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it4 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppstg_tmp_16_reg_791_pp0_it4 );

    SC_METHOD(thread_dst_data_stream_0_V_write);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it4 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_exitcond1_fu_376_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( src_rows_V_read );
    sensitive << ( t_V_5_reg_215 );

    SC_METHOD(thread_exitcond_fu_411_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( src_cols_V_read );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( t_V_phi_fu_231_p4 );

    SC_METHOD(thread_i_V_fu_381_p2);
    sensitive << ( t_V_5_reg_215 );

    SC_METHOD(thread_j_V_fu_416_p2);
    sensitive << ( t_V_phi_fu_231_p4 );

    SC_METHOD(thread_left_3_fu_639_p3);
    sensitive << ( right_6_reg_811 );
    sensitive << ( left_1_fu_92 );
    sensitive << ( sel_tmp8_fu_634_p2 );

    SC_METHOD(thread_left_4_fu_660_p3);
    sensitive << ( sel_tmp4_reg_828 );
    sensitive << ( left_1_fu_92 );
    sensitive << ( left_6_fu_653_p3 );

    SC_METHOD(thread_left_5_fu_646_p3);
    sensitive << ( ap_reg_ppstg_or_cond_reg_797_pp0_it3 );
    sensitive << ( left_1_fu_92 );
    sensitive << ( left_3_fu_639_p3 );

    SC_METHOD(thread_left_6_fu_653_p3);
    sensitive << ( sel_tmp9_demorgan_reg_817 );
    sensitive << ( left_1_fu_92 );
    sensitive << ( left_5_fu_646_p3 );

    SC_METHOD(thread_left_fu_320_p1);
    sensitive << ( src_cols_V_read );

    SC_METHOD(thread_not4_fu_391_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( op2_assign_8_reg_722 );
    sensitive << ( exitcond1_fu_376_p2 );
    sensitive << ( tmp_45_cast_fu_387_p1 );

    SC_METHOD(thread_not5_fu_396_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( op2_assign_3_reg_737 );
    sensitive << ( exitcond1_fu_376_p2 );
    sensitive << ( tmp_45_cast_fu_387_p1 );

    SC_METHOD(thread_not6_fu_431_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( op2_assign_9_reg_727 );
    sensitive << ( exitcond_fu_411_p2 );
    sensitive << ( tmp_47_cast_fu_422_p1 );

    SC_METHOD(thread_not9_fu_426_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( op2_assign_reg_732 );
    sensitive << ( exitcond_fu_411_p2 );
    sensitive << ( tmp_47_cast_fu_422_p1 );

    SC_METHOD(thread_not_fu_446_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppstg_t_V_reg_227_pp0_it1 );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it1 );

    SC_METHOD(thread_op2_assign_3_fu_350_p2);
    sensitive << ( retval_i_cast_fu_324_p1 );

    SC_METHOD(thread_op2_assign_8_fu_328_p2);
    sensitive << ( retval_i_cast_fu_324_p1 );

    SC_METHOD(thread_op2_assign_9_fu_338_p2);
    sensitive << ( retval_i5_cast_fu_334_p1 );

    SC_METHOD(thread_op2_assign_fu_344_p2);
    sensitive << ( retval_i5_cast_fu_334_p1 );

    SC_METHOD(thread_or_cond1_fu_436_p2);
    sensitive << ( not4_reg_750 );
    sensitive << ( not6_fu_431_p2 );

    SC_METHOD(thread_or_cond_fu_452_p2);
    sensitive << ( p_not_fu_441_p2 );
    sensitive << ( not_fu_446_p2 );

    SC_METHOD(thread_p_not_fu_441_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it1 );
    sensitive << ( tmp_16_reg_791 );

    SC_METHOD(thread_retval_i5_cast_fu_334_p1);
    sensitive << ( src_cols_V_read );

    SC_METHOD(thread_retval_i_cast_fu_324_p1);
    sensitive << ( src_rows_V_read );

    SC_METHOD(thread_right_1_fu_557_p3);
    sensitive << ( sel_tmp4_fu_514_p2 );
    sensitive << ( right_fu_88 );
    sensitive << ( right_5_fu_549_p3 );

    SC_METHOD(thread_right_3_fu_498_p3);
    sensitive << ( right_6_fu_488_p1 );
    sensitive << ( right_fu_88 );
    sensitive << ( tmp_7_fu_492_p2 );

    SC_METHOD(thread_right_4_fu_542_p3);
    sensitive << ( or_cond_reg_797 );
    sensitive << ( right_fu_88 );
    sensitive << ( right_3_fu_498_p3 );

    SC_METHOD(thread_right_5_fu_549_p3);
    sensitive << ( sel_tmp9_demorgan_fu_506_p2 );
    sensitive << ( right_fu_88 );
    sensitive << ( right_4_fu_542_p3 );

    SC_METHOD(thread_right_6_fu_488_p1);
    sensitive << ( ap_reg_ppstg_t_V_reg_227_pp0_it2 );

    SC_METHOD(thread_sel_tmp1_demorgan_fu_458_p2);
    sensitive << ( p_not_fu_441_p2 );
    sensitive << ( not_fu_446_p2 );

    SC_METHOD(thread_sel_tmp1_fu_464_p2);
    sensitive << ( sel_tmp1_demorgan_fu_458_p2 );

    SC_METHOD(thread_sel_tmp2_fu_510_p2);
    sensitive << ( ap_reg_ppstg_not9_reg_781_pp0_it2 );
    sensitive << ( sel_tmp1_reg_806 );

    SC_METHOD(thread_sel_tmp3_fu_405_p2);
    sensitive << ( not5_fu_396_p2 );

    SC_METHOD(thread_sel_tmp4_fu_514_p2);
    sensitive << ( sel_tmp3_reg_767 );
    sensitive << ( sel_tmp2_fu_510_p2 );

    SC_METHOD(thread_sel_tmp6_fu_607_p3);
    sensitive << ( ap_reg_ppstg_or_cond_reg_797_pp0_it3 );
    sensitive << ( top_2_fu_100 );
    sensitive << ( top_5_cast_fu_598_p1 );

    SC_METHOD(thread_sel_tmp8_fu_634_p2);
    sensitive << ( sel_tmp2_reg_823 );
    sensitive << ( tmp2_fu_629_p2 );

    SC_METHOD(thread_sel_tmp9_demorgan_fu_506_p2);
    sensitive << ( ap_reg_ppstg_not9_reg_781_pp0_it2 );
    sensitive << ( or_cond_reg_797 );

    SC_METHOD(thread_sel_tmp_fu_614_p3);
    sensitive << ( sel_tmp9_demorgan_reg_817 );
    sensitive << ( top_2_fu_100 );
    sensitive << ( sel_tmp6_fu_607_p3 );

    SC_METHOD(thread_src_data_stream_0_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_772 );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_t_V_phi_fu_231_p4);
    sensitive << ( ap_CS_fsm );
    sensitive << ( t_V_reg_227 );
    sensitive << ( exitcond_reg_772 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( j_V_reg_776 );

    SC_METHOD(thread_tmp2_fu_629_p2);
    sensitive << ( not5_reg_755 );
    sensitive << ( tmp_8_fu_602_p2 );

    SC_METHOD(thread_tmp_11_fu_265_p5);
    sensitive << ( guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns );

    SC_METHOD(thread_tmp_12_fu_278_p1);
    sensitive << ( guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns_1 );

    SC_METHOD(thread_tmp_13_fu_303_p5);
    sensitive << ( guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns_1 );

    SC_METHOD(thread_tmp_15_fu_586_p1);
    sensitive << ( top_2_fu_100 );

    SC_METHOD(thread_tmp_3_fu_282_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_106 );
    sensitive << ( tmp_12_fu_278_p1 );

    SC_METHOD(thread_tmp_45_cast_fu_387_p1);
    sensitive << ( t_V_5_reg_215 );

    SC_METHOD(thread_tmp_47_cast_fu_422_p1);
    sensitive << ( t_V_phi_fu_231_p4 );

    SC_METHOD(thread_tmp_47_i_cast_fu_250_p1);
    sensitive << ( src_rows_V_read );

    SC_METHOD(thread_tmp_48_i_cast_fu_260_p1);
    sensitive << ( tmp_48_i_fu_254_p2 );

    SC_METHOD(thread_tmp_48_i_fu_254_p2);
    sensitive << ( tmp_47_i_cast_fu_250_p1 );

    SC_METHOD(thread_tmp_50_i_cast_fu_288_p1);
    sensitive << ( src_cols_V_read );

    SC_METHOD(thread_tmp_51_i_cast_fu_298_p1);
    sensitive << ( tmp_51_i_fu_292_p2 );

    SC_METHOD(thread_tmp_51_i_fu_292_p2);
    sensitive << ( tmp_50_i_cast_fu_288_p1 );

    SC_METHOD(thread_tmp_5_fu_476_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( bottom_6_reg_760 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it2 );
    sensitive << ( or_cond_reg_797 );
    sensitive << ( bottom_fu_96 );

    SC_METHOD(thread_tmp_6_fu_581_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( bottom_6_reg_760 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it3 );
    sensitive << ( ap_reg_ppstg_or_cond_reg_797_pp0_it3 );
    sensitive << ( sel_tmp9_demorgan_reg_817 );
    sensitive << ( sel_tmp4_reg_828 );
    sensitive << ( top_2_fu_100 );

    SC_METHOD(thread_tmp_7_fu_492_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it2 );
    sensitive << ( or_cond_reg_797 );
    sensitive << ( right_6_fu_488_p1 );
    sensitive << ( right_fu_88 );

    SC_METHOD(thread_tmp_8_fu_602_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_772_pp0_it3 );
    sensitive << ( ap_reg_ppstg_or_cond_reg_797_pp0_it3 );
    sensitive << ( right_6_reg_811 );
    sensitive << ( sel_tmp9_demorgan_reg_817 );
    sensitive << ( sel_tmp4_reg_828 );
    sensitive << ( left_1_fu_92 );

    SC_METHOD(thread_tmp_fu_240_p1);
    sensitive << ( guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns );

    SC_METHOD(thread_tmp_s_fu_244_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_106 );
    sensitive << ( tmp_fu_240_p1 );

    SC_METHOD(thread_top_1_fu_621_p3);
    sensitive << ( sel_tmp4_reg_828 );
    sensitive << ( top_2_fu_100 );
    sensitive << ( sel_tmp_fu_614_p3 );

    SC_METHOD(thread_top_4_fu_590_p3);
    sensitive << ( t_V_5_reg_215 );
    sensitive << ( tmp_6_fu_581_p2 );
    sensitive << ( tmp_15_fu_586_p1 );

    SC_METHOD(thread_top_5_cast_fu_598_p1);
    sensitive << ( top_4_fu_590_p3 );

    SC_METHOD(thread_top_fu_316_p1);
    sensitive << ( src_rows_V_read );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_67 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_sig_bdd_93 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_sig_bdd_106 );
    sensitive << ( exitcond1_fu_376_p2 );
    sensitive << ( exitcond_fu_411_p2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00";
    guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns = "0000000000000000000000000000000000000000000000000000000000000000";
    p_bottom = "00000000000000000000000000000000";
    guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns_1 = "0000000000000000000000000000000000000000000000000000000000000000";
    p_right = "00000000000000000000000000000000";
    p_top = "00000000000000000000000000000000";
    p_left = "00000000000000000000000000000000";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it5 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "bounding_box_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    const char* dump_vcd = std::getenv("AP_WRITE_VCD");
    if (dump_vcd && string(dump_vcd) == "1" ) {
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, src_rows_V_read, "(port)src_rows_V_read");
    sc_trace(mVcdFile, src_cols_V_read, "(port)src_cols_V_read");
    sc_trace(mVcdFile, src_data_stream_0_V_dout, "(port)src_data_stream_0_V_dout");
    sc_trace(mVcdFile, src_data_stream_0_V_empty_n, "(port)src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, src_data_stream_0_V_read, "(port)src_data_stream_0_V_read");
    sc_trace(mVcdFile, dst_data_stream_0_V_din, "(port)dst_data_stream_0_V_din");
    sc_trace(mVcdFile, dst_data_stream_0_V_full_n, "(port)dst_data_stream_0_V_full_n");
    sc_trace(mVcdFile, dst_data_stream_0_V_write, "(port)dst_data_stream_0_V_write");
    sc_trace(mVcdFile, bb_top_V_din, "(port)bb_top_V_din");
    sc_trace(mVcdFile, bb_top_V_full_n, "(port)bb_top_V_full_n");
    sc_trace(mVcdFile, bb_top_V_write, "(port)bb_top_V_write");
    sc_trace(mVcdFile, bb_bottom_V_din, "(port)bb_bottom_V_din");
    sc_trace(mVcdFile, bb_bottom_V_full_n, "(port)bb_bottom_V_full_n");
    sc_trace(mVcdFile, bb_bottom_V_write, "(port)bb_bottom_V_write");
    sc_trace(mVcdFile, bb_left_V_din, "(port)bb_left_V_din");
    sc_trace(mVcdFile, bb_left_V_full_n, "(port)bb_left_V_full_n");
    sc_trace(mVcdFile, bb_left_V_write, "(port)bb_left_V_write");
    sc_trace(mVcdFile, bb_right_V_din, "(port)bb_right_V_din");
    sc_trace(mVcdFile, bb_right_V_full_n, "(port)bb_right_V_full_n");
    sc_trace(mVcdFile, bb_right_V_write, "(port)bb_right_V_write");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns, "guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns");
    sc_trace(mVcdFile, p_bottom, "p_bottom");
    sc_trace(mVcdFile, guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns_1, "guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns_1");
    sc_trace(mVcdFile, p_right, "p_right");
    sc_trace(mVcdFile, p_top, "p_top");
    sc_trace(mVcdFile, p_left, "p_left");
    sc_trace(mVcdFile, t_V_reg_227, "t_V_reg_227");
    sc_trace(mVcdFile, ap_reg_ppstg_t_V_reg_227_pp0_it1, "ap_reg_ppstg_t_V_reg_227_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, exitcond_reg_772, "exitcond_reg_772");
    sc_trace(mVcdFile, ap_sig_bdd_67, "ap_sig_bdd_67");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_772_pp0_it4, "ap_reg_ppstg_exitcond_reg_772_pp0_it4");
    sc_trace(mVcdFile, ap_sig_bdd_93, "ap_sig_bdd_93");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it5, "ap_reg_ppiten_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppstg_t_V_reg_227_pp0_it2, "ap_reg_ppstg_t_V_reg_227_pp0_it2");
    sc_trace(mVcdFile, ap_sig_bdd_106, "ap_sig_bdd_106");
    sc_trace(mVcdFile, op2_assign_8_fu_328_p2, "op2_assign_8_fu_328_p2");
    sc_trace(mVcdFile, op2_assign_8_reg_722, "op2_assign_8_reg_722");
    sc_trace(mVcdFile, op2_assign_9_fu_338_p2, "op2_assign_9_fu_338_p2");
    sc_trace(mVcdFile, op2_assign_9_reg_727, "op2_assign_9_reg_727");
    sc_trace(mVcdFile, op2_assign_fu_344_p2, "op2_assign_fu_344_p2");
    sc_trace(mVcdFile, op2_assign_reg_732, "op2_assign_reg_732");
    sc_trace(mVcdFile, op2_assign_3_fu_350_p2, "op2_assign_3_fu_350_p2");
    sc_trace(mVcdFile, op2_assign_3_reg_737, "op2_assign_3_reg_737");
    sc_trace(mVcdFile, i_V_fu_381_p2, "i_V_fu_381_p2");
    sc_trace(mVcdFile, i_V_reg_745, "i_V_reg_745");
    sc_trace(mVcdFile, not4_fu_391_p2, "not4_fu_391_p2");
    sc_trace(mVcdFile, not4_reg_750, "not4_reg_750");
    sc_trace(mVcdFile, exitcond1_fu_376_p2, "exitcond1_fu_376_p2");
    sc_trace(mVcdFile, not5_fu_396_p2, "not5_fu_396_p2");
    sc_trace(mVcdFile, not5_reg_755, "not5_reg_755");
    sc_trace(mVcdFile, bottom_6_fu_401_p1, "bottom_6_fu_401_p1");
    sc_trace(mVcdFile, bottom_6_reg_760, "bottom_6_reg_760");
    sc_trace(mVcdFile, sel_tmp3_fu_405_p2, "sel_tmp3_fu_405_p2");
    sc_trace(mVcdFile, sel_tmp3_reg_767, "sel_tmp3_reg_767");
    sc_trace(mVcdFile, exitcond_fu_411_p2, "exitcond_fu_411_p2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_772_pp0_it1, "ap_reg_ppstg_exitcond_reg_772_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_772_pp0_it2, "ap_reg_ppstg_exitcond_reg_772_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_772_pp0_it3, "ap_reg_ppstg_exitcond_reg_772_pp0_it3");
    sc_trace(mVcdFile, j_V_fu_416_p2, "j_V_fu_416_p2");
    sc_trace(mVcdFile, j_V_reg_776, "j_V_reg_776");
    sc_trace(mVcdFile, not9_fu_426_p2, "not9_fu_426_p2");
    sc_trace(mVcdFile, not9_reg_781, "not9_reg_781");
    sc_trace(mVcdFile, ap_reg_ppstg_not9_reg_781_pp0_it1, "ap_reg_ppstg_not9_reg_781_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_not9_reg_781_pp0_it2, "ap_reg_ppstg_not9_reg_781_pp0_it2");
    sc_trace(mVcdFile, or_cond1_fu_436_p2, "or_cond1_fu_436_p2");
    sc_trace(mVcdFile, or_cond1_reg_787, "or_cond1_reg_787");
    sc_trace(mVcdFile, ap_reg_ppstg_or_cond1_reg_787_pp0_it1, "ap_reg_ppstg_or_cond1_reg_787_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_or_cond1_reg_787_pp0_it2, "ap_reg_ppstg_or_cond1_reg_787_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_or_cond1_reg_787_pp0_it3, "ap_reg_ppstg_or_cond1_reg_787_pp0_it3");
    sc_trace(mVcdFile, tmp_16_reg_791, "tmp_16_reg_791");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_16_reg_791_pp0_it2, "ap_reg_ppstg_tmp_16_reg_791_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_16_reg_791_pp0_it3, "ap_reg_ppstg_tmp_16_reg_791_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_16_reg_791_pp0_it4, "ap_reg_ppstg_tmp_16_reg_791_pp0_it4");
    sc_trace(mVcdFile, or_cond_fu_452_p2, "or_cond_fu_452_p2");
    sc_trace(mVcdFile, or_cond_reg_797, "or_cond_reg_797");
    sc_trace(mVcdFile, ap_reg_ppstg_or_cond_reg_797_pp0_it3, "ap_reg_ppstg_or_cond_reg_797_pp0_it3");
    sc_trace(mVcdFile, sel_tmp1_fu_464_p2, "sel_tmp1_fu_464_p2");
    sc_trace(mVcdFile, sel_tmp1_reg_806, "sel_tmp1_reg_806");
    sc_trace(mVcdFile, right_6_fu_488_p1, "right_6_fu_488_p1");
    sc_trace(mVcdFile, right_6_reg_811, "right_6_reg_811");
    sc_trace(mVcdFile, sel_tmp9_demorgan_fu_506_p2, "sel_tmp9_demorgan_fu_506_p2");
    sc_trace(mVcdFile, sel_tmp9_demorgan_reg_817, "sel_tmp9_demorgan_reg_817");
    sc_trace(mVcdFile, sel_tmp2_fu_510_p2, "sel_tmp2_fu_510_p2");
    sc_trace(mVcdFile, sel_tmp2_reg_823, "sel_tmp2_reg_823");
    sc_trace(mVcdFile, sel_tmp4_fu_514_p2, "sel_tmp4_fu_514_p2");
    sc_trace(mVcdFile, sel_tmp4_reg_828, "sel_tmp4_reg_828");
    sc_trace(mVcdFile, bottom_1_fu_534_p3, "bottom_1_fu_534_p3");
    sc_trace(mVcdFile, bottom_1_reg_834, "bottom_1_reg_834");
    sc_trace(mVcdFile, right_1_fu_557_p3, "right_1_fu_557_p3");
    sc_trace(mVcdFile, right_1_reg_839, "right_1_reg_839");
    sc_trace(mVcdFile, t_V_5_reg_215, "t_V_5_reg_215");
    sc_trace(mVcdFile, ap_reg_phibuf_t_V_5_reg_215, "ap_reg_phibuf_t_V_5_reg_215");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, t_V_phi_fu_231_p4, "t_V_phi_fu_231_p4");
    sc_trace(mVcdFile, tmp_11_fu_265_p5, "tmp_11_fu_265_p5");
    sc_trace(mVcdFile, tmp_s_fu_244_p2, "tmp_s_fu_244_p2");
    sc_trace(mVcdFile, tmp_48_i_cast_fu_260_p1, "tmp_48_i_cast_fu_260_p1");
    sc_trace(mVcdFile, tmp_13_fu_303_p5, "tmp_13_fu_303_p5");
    sc_trace(mVcdFile, tmp_3_fu_282_p2, "tmp_3_fu_282_p2");
    sc_trace(mVcdFile, tmp_51_i_cast_fu_298_p1, "tmp_51_i_cast_fu_298_p1");
    sc_trace(mVcdFile, top_1_fu_621_p3, "top_1_fu_621_p3");
    sc_trace(mVcdFile, left_4_fu_660_p3, "left_4_fu_660_p3");
    sc_trace(mVcdFile, right_fu_88, "right_fu_88");
    sc_trace(mVcdFile, left_1_fu_92, "left_1_fu_92");
    sc_trace(mVcdFile, left_fu_320_p1, "left_fu_320_p1");
    sc_trace(mVcdFile, bottom_fu_96, "bottom_fu_96");
    sc_trace(mVcdFile, top_2_fu_100, "top_2_fu_100");
    sc_trace(mVcdFile, top_fu_316_p1, "top_fu_316_p1");
    sc_trace(mVcdFile, tmp_fu_240_p1, "tmp_fu_240_p1");
    sc_trace(mVcdFile, tmp_47_i_cast_fu_250_p1, "tmp_47_i_cast_fu_250_p1");
    sc_trace(mVcdFile, tmp_48_i_fu_254_p2, "tmp_48_i_fu_254_p2");
    sc_trace(mVcdFile, tmp_12_fu_278_p1, "tmp_12_fu_278_p1");
    sc_trace(mVcdFile, tmp_50_i_cast_fu_288_p1, "tmp_50_i_cast_fu_288_p1");
    sc_trace(mVcdFile, tmp_51_i_fu_292_p2, "tmp_51_i_fu_292_p2");
    sc_trace(mVcdFile, retval_i_cast_fu_324_p1, "retval_i_cast_fu_324_p1");
    sc_trace(mVcdFile, retval_i5_cast_fu_334_p1, "retval_i5_cast_fu_334_p1");
    sc_trace(mVcdFile, tmp_45_cast_fu_387_p1, "tmp_45_cast_fu_387_p1");
    sc_trace(mVcdFile, tmp_47_cast_fu_422_p1, "tmp_47_cast_fu_422_p1");
    sc_trace(mVcdFile, not6_fu_431_p2, "not6_fu_431_p2");
    sc_trace(mVcdFile, p_not_fu_441_p2, "p_not_fu_441_p2");
    sc_trace(mVcdFile, not_fu_446_p2, "not_fu_446_p2");
    sc_trace(mVcdFile, sel_tmp1_demorgan_fu_458_p2, "sel_tmp1_demorgan_fu_458_p2");
    sc_trace(mVcdFile, tmp_5_fu_476_p2, "tmp_5_fu_476_p2");
    sc_trace(mVcdFile, tmp_7_fu_492_p2, "tmp_7_fu_492_p2");
    sc_trace(mVcdFile, bottom_3_fu_481_p3, "bottom_3_fu_481_p3");
    sc_trace(mVcdFile, bottom_4_fu_519_p3, "bottom_4_fu_519_p3");
    sc_trace(mVcdFile, bottom_5_fu_526_p3, "bottom_5_fu_526_p3");
    sc_trace(mVcdFile, right_3_fu_498_p3, "right_3_fu_498_p3");
    sc_trace(mVcdFile, right_4_fu_542_p3, "right_4_fu_542_p3");
    sc_trace(mVcdFile, right_5_fu_549_p3, "right_5_fu_549_p3");
    sc_trace(mVcdFile, tmp_6_fu_581_p2, "tmp_6_fu_581_p2");
    sc_trace(mVcdFile, tmp_15_fu_586_p1, "tmp_15_fu_586_p1");
    sc_trace(mVcdFile, top_4_fu_590_p3, "top_4_fu_590_p3");
    sc_trace(mVcdFile, top_5_cast_fu_598_p1, "top_5_cast_fu_598_p1");
    sc_trace(mVcdFile, sel_tmp6_fu_607_p3, "sel_tmp6_fu_607_p3");
    sc_trace(mVcdFile, sel_tmp_fu_614_p3, "sel_tmp_fu_614_p3");
    sc_trace(mVcdFile, tmp_8_fu_602_p2, "tmp_8_fu_602_p2");
    sc_trace(mVcdFile, tmp2_fu_629_p2, "tmp2_fu_629_p2");
    sc_trace(mVcdFile, sel_tmp8_fu_634_p2, "sel_tmp8_fu_634_p2");
    sc_trace(mVcdFile, left_3_fu_639_p3, "left_3_fu_639_p3");
    sc_trace(mVcdFile, left_5_fu_646_p3, "left_5_fu_646_p3");
    sc_trace(mVcdFile, left_6_fu_653_p3, "left_6_fu_653_p3");

    }
}

bounding_box::~bounding_box() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void bounding_box::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                    !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_376_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
             !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_411_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_376_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
             !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_411_p2.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_376_p2.read())) || 
                    (esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
                     !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_411_p2.read())))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
             !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        } else if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_376_p2.read()))) {
            ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
             !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        } else if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_376_p2.read()))) {
            ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
             !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        } else if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_376_p2.read()))) {
            ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it5 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
             !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
            ap_reg_ppiten_pp0_it5 = ap_reg_ppiten_pp0_it4.read();
        } else if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_376_p2.read()))) {
            ap_reg_ppiten_pp0_it5 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && 
         !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it2.read()))) {
        bottom_fu_96 = bottom_1_fu_534_p3.read();
    } else if ((esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !ap_sig_bdd_106.read())) {
        bottom_fu_96 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
         !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it3.read()))) {
        left_1_fu_92 = left_4_fu_660_p3.read();
    } else if ((esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !ap_sig_bdd_106.read())) {
        left_1_fu_92 = left_fu_320_p1.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
         !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_787_pp0_it3.read()))) {
        p_bottom = bottom_1_reg_834.read();
    } else if ((esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !ap_sig_bdd_106.read() && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_244_p2.read()))) {
        p_bottom = tmp_48_i_cast_fu_260_p1.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
         !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_787_pp0_it3.read()))) {
        p_right = right_1_reg_839.read();
    } else if ((esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !ap_sig_bdd_106.read() && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_282_p2.read()))) {
        p_right = tmp_51_i_cast_fu_298_p1.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && 
         !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it2.read()))) {
        right_fu_88 = right_1_fu_557_p3.read();
    } else if ((esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !ap_sig_bdd_106.read())) {
        right_fu_88 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_411_p2.read()) && 
         esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_NS_fsm.read()))) {
        t_V_5_reg_215 = i_V_reg_745.read();
    } else if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
                esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_NS_fsm.read()))) {
        t_V_5_reg_215 = ap_reg_phibuf_t_V_5_reg_215.read();
    } else if ((esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !ap_sig_bdd_106.read())) {
        t_V_5_reg_215 = ap_const_lv12_0;
    }
    if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_376_p2.read()))) {
        t_V_reg_227 = ap_const_lv12_0;
    } else if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(exitcond_reg_772.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
                !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
        t_V_reg_227 = j_V_reg_776.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
         !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it3.read()))) {
        top_2_fu_100 = top_1_fu_621_p3.read();
    } else if ((esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !ap_sig_bdd_106.read())) {
        top_2_fu_100 = top_fu_316_p1.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_411_p2.read()))) {
        ap_reg_phibuf_t_V_5_reg_215 = i_V_reg_745.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
        ap_reg_ppstg_exitcond_reg_772_pp0_it1 = exitcond_reg_772.read();
        ap_reg_ppstg_exitcond_reg_772_pp0_it2 = ap_reg_ppstg_exitcond_reg_772_pp0_it1.read();
        ap_reg_ppstg_exitcond_reg_772_pp0_it3 = ap_reg_ppstg_exitcond_reg_772_pp0_it2.read();
        ap_reg_ppstg_exitcond_reg_772_pp0_it4 = ap_reg_ppstg_exitcond_reg_772_pp0_it3.read();
        ap_reg_ppstg_not9_reg_781_pp0_it1 = not9_reg_781.read();
        ap_reg_ppstg_not9_reg_781_pp0_it2 = ap_reg_ppstg_not9_reg_781_pp0_it1.read();
        ap_reg_ppstg_or_cond1_reg_787_pp0_it1 = or_cond1_reg_787.read();
        ap_reg_ppstg_or_cond1_reg_787_pp0_it2 = ap_reg_ppstg_or_cond1_reg_787_pp0_it1.read();
        ap_reg_ppstg_or_cond1_reg_787_pp0_it3 = ap_reg_ppstg_or_cond1_reg_787_pp0_it2.read();
        ap_reg_ppstg_or_cond_reg_797_pp0_it3 = or_cond_reg_797.read();
        ap_reg_ppstg_t_V_reg_227_pp0_it1 = t_V_reg_227.read();
        ap_reg_ppstg_t_V_reg_227_pp0_it2 = ap_reg_ppstg_t_V_reg_227_pp0_it1.read();
        ap_reg_ppstg_tmp_16_reg_791_pp0_it2 = tmp_16_reg_791.read();
        ap_reg_ppstg_tmp_16_reg_791_pp0_it3 = ap_reg_ppstg_tmp_16_reg_791_pp0_it2.read();
        ap_reg_ppstg_tmp_16_reg_791_pp0_it4 = ap_reg_ppstg_tmp_16_reg_791_pp0_it3.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it2.read()))) {
        bottom_1_reg_834 = bottom_1_fu_534_p3.read();
        right_1_reg_839 = right_1_fu_557_p3.read();
        right_6_reg_811 = right_6_fu_488_p1.read();
        sel_tmp2_reg_823 = sel_tmp2_fu_510_p2.read();
        sel_tmp4_reg_828 = sel_tmp4_fu_514_p2.read();
        sel_tmp9_demorgan_reg_817 = sel_tmp9_demorgan_fu_506_p2.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_376_p2.read()))) {
        bottom_6_reg_760 = bottom_6_fu_401_p1.read();
        not4_reg_750 = not4_fu_391_p2.read();
        not5_reg_755 = not5_fu_396_p2.read();
        sel_tmp3_reg_767 = sel_tmp3_fu_405_p2.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
        exitcond_reg_772 = exitcond_fu_411_p2.read();
        j_V_reg_776 = j_V_fu_416_p2.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && !ap_sig_bdd_106.read() && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_244_p2.read()))) {
        guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns = tmp_11_fu_265_p5.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && !ap_sig_bdd_106.read() && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_282_p2.read()))) {
        guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns_1 = tmp_13_fu_303_p5.read();
    }
    if (esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        i_V_reg_745 = i_V_fu_381_p2.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_411_p2.read()))) {
        not9_reg_781 = not9_fu_426_p2.read();
        or_cond1_reg_787 = or_cond1_fu_436_p2.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && !ap_sig_bdd_106.read())) {
        op2_assign_3_reg_737 = op2_assign_3_fu_350_p2.read();
        op2_assign_8_reg_722 = op2_assign_8_fu_328_p2.read();
        op2_assign_9_reg_727 = op2_assign_9_fu_338_p2.read();
        op2_assign_reg_732 = op2_assign_fu_344_p2.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it1.read()))) {
        or_cond_reg_797 = or_cond_fu_452_p2.read();
        sel_tmp1_reg_806 = sel_tmp1_fu_464_p2.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it3.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_787_pp0_it3.read()))) {
        p_left = left_4_fu_660_p3.read();
        p_top = top_1_fu_621_p3.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(exitcond_reg_772.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
        tmp_16_reg_791 = src_data_stream_0_V_dout.read();
    }
}

void bounding_box::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_376_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void bounding_box::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void bounding_box::thread_ap_ready() {
    if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_376_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void bounding_box::thread_ap_sig_bdd_106() {
    ap_sig_bdd_106 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void bounding_box::thread_ap_sig_bdd_67() {
    ap_sig_bdd_67 = (esl_seteq<1,1,1>(src_data_stream_0_V_empty_n.read(), ap_const_logic_0) && esl_seteq<1,1,1>(exitcond_reg_772.read(), ap_const_lv1_0));
}

void bounding_box::thread_ap_sig_bdd_93() {
    ap_sig_bdd_93 = ((esl_seteq<1,1,1>(bb_top_V_full_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it4.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it4.read()) && 
  esl_seteq<1,1,1>(bb_bottom_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it4.read()) && 
  esl_seteq<1,1,1>(bb_left_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it4.read()) && 
  esl_seteq<1,1,1>(bb_right_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it4.read()) && 
  esl_seteq<1,1,1>(dst_data_stream_0_V_full_n.read(), ap_const_logic_0)));
}

void bounding_box::thread_bb_bottom_V_din() {
    bb_bottom_V_din = p_bottom.read();
}

void bounding_box::thread_bb_bottom_V_write() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
         !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
        bb_bottom_V_write = ap_const_logic_1;
    } else {
        bb_bottom_V_write = ap_const_logic_0;
    }
}

void bounding_box::thread_bb_left_V_din() {
    bb_left_V_din = p_left.read();
}

void bounding_box::thread_bb_left_V_write() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
         !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
        bb_left_V_write = ap_const_logic_1;
    } else {
        bb_left_V_write = ap_const_logic_0;
    }
}

void bounding_box::thread_bb_right_V_din() {
    bb_right_V_din = p_right.read();
}

void bounding_box::thread_bb_right_V_write() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
         !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
        bb_right_V_write = ap_const_logic_1;
    } else {
        bb_right_V_write = ap_const_logic_0;
    }
}

void bounding_box::thread_bb_top_V_din() {
    bb_top_V_din = p_top.read();
}

void bounding_box::thread_bb_top_V_write() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
         !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
        bb_top_V_write = ap_const_logic_1;
    } else {
        bb_top_V_write = ap_const_logic_0;
    }
}

void bounding_box::thread_bottom_1_fu_534_p3() {
    bottom_1_fu_534_p3 = (!sel_tmp4_fu_514_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_fu_514_p2.read()[0].to_bool())? bottom_fu_96.read(): bottom_5_fu_526_p3.read());
}

void bounding_box::thread_bottom_3_fu_481_p3() {
    bottom_3_fu_481_p3 = (!tmp_5_fu_476_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_5_fu_476_p2.read()[0].to_bool())? bottom_6_reg_760.read(): bottom_fu_96.read());
}

void bounding_box::thread_bottom_4_fu_519_p3() {
    bottom_4_fu_519_p3 = (!or_cond_reg_797.read()[0].is_01())? sc_lv<32>(): ((or_cond_reg_797.read()[0].to_bool())? bottom_fu_96.read(): bottom_3_fu_481_p3.read());
}

void bounding_box::thread_bottom_5_fu_526_p3() {
    bottom_5_fu_526_p3 = (!sel_tmp9_demorgan_fu_506_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp9_demorgan_fu_506_p2.read()[0].to_bool())? bottom_4_fu_519_p3.read(): bottom_fu_96.read());
}

void bounding_box::thread_bottom_6_fu_401_p1() {
    bottom_6_fu_401_p1 = esl_zext<32,12>(t_V_5_reg_215.read());
}

void bounding_box::thread_dst_data_stream_0_V_din() {
    dst_data_stream_0_V_din = ap_reg_ppstg_tmp_16_reg_791_pp0_it4.read();
}

void bounding_box::thread_dst_data_stream_0_V_write() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_772_pp0_it4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
         !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
        dst_data_stream_0_V_write = ap_const_logic_1;
    } else {
        dst_data_stream_0_V_write = ap_const_logic_0;
    }
}

void bounding_box::thread_exitcond1_fu_376_p2() {
    exitcond1_fu_376_p2 = (!t_V_5_reg_215.read().is_01() || !src_rows_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_5_reg_215.read() == src_rows_V_read.read());
}

void bounding_box::thread_exitcond_fu_411_p2() {
    exitcond_fu_411_p2 = (!t_V_phi_fu_231_p4.read().is_01() || !src_cols_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_phi_fu_231_p4.read() == src_cols_V_read.read());
}

void bounding_box::thread_i_V_fu_381_p2() {
    i_V_fu_381_p2 = (!t_V_5_reg_215.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_bigint<12>(t_V_5_reg_215.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void bounding_box::thread_j_V_fu_416_p2() {
    j_V_fu_416_p2 = (!t_V_phi_fu_231_p4.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_bigint<12>(t_V_phi_fu_231_p4.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void bounding_box::thread_left_3_fu_639_p3() {
    left_3_fu_639_p3 = (!sel_tmp8_fu_634_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp8_fu_634_p2.read()[0].to_bool())? right_6_reg_811.read(): left_1_fu_92.read());
}

void bounding_box::thread_left_4_fu_660_p3() {
    left_4_fu_660_p3 = (!sel_tmp4_reg_828.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_828.read()[0].to_bool())? left_1_fu_92.read(): left_6_fu_653_p3.read());
}

void bounding_box::thread_left_5_fu_646_p3() {
    left_5_fu_646_p3 = (!ap_reg_ppstg_or_cond_reg_797_pp0_it3.read()[0].is_01())? sc_lv<32>(): ((ap_reg_ppstg_or_cond_reg_797_pp0_it3.read()[0].to_bool())? left_1_fu_92.read(): left_3_fu_639_p3.read());
}

void bounding_box::thread_left_6_fu_653_p3() {
    left_6_fu_653_p3 = (!sel_tmp9_demorgan_reg_817.read()[0].is_01())? sc_lv<32>(): ((sel_tmp9_demorgan_reg_817.read()[0].to_bool())? left_5_fu_646_p3.read(): left_1_fu_92.read());
}

void bounding_box::thread_left_fu_320_p1() {
    left_fu_320_p1 = esl_zext<32,12>(src_cols_V_read.read());
}

void bounding_box::thread_not4_fu_391_p2() {
    not4_fu_391_p2 = (!tmp_45_cast_fu_387_p1.read().is_01() || !op2_assign_8_reg_722.read().is_01())? sc_lv<1>(): sc_lv<1>(tmp_45_cast_fu_387_p1.read() == op2_assign_8_reg_722.read());
}

void bounding_box::thread_not5_fu_396_p2() {
    not5_fu_396_p2 = (!tmp_45_cast_fu_387_p1.read().is_01() || !op2_assign_3_reg_737.read().is_01())? sc_lv<1>(): (sc_biguint<13>(tmp_45_cast_fu_387_p1.read()) < sc_biguint<13>(op2_assign_3_reg_737.read()));
}

void bounding_box::thread_not6_fu_431_p2() {
    not6_fu_431_p2 = (!tmp_47_cast_fu_422_p1.read().is_01() || !op2_assign_9_reg_727.read().is_01())? sc_lv<1>(): sc_lv<1>(tmp_47_cast_fu_422_p1.read() == op2_assign_9_reg_727.read());
}

void bounding_box::thread_not9_fu_426_p2() {
    not9_fu_426_p2 = (!tmp_47_cast_fu_422_p1.read().is_01() || !op2_assign_reg_732.read().is_01())? sc_lv<1>(): (sc_biguint<13>(tmp_47_cast_fu_422_p1.read()) < sc_biguint<13>(op2_assign_reg_732.read()));
}

void bounding_box::thread_not_fu_446_p2() {
    not_fu_446_p2 = (!ap_reg_ppstg_t_V_reg_227_pp0_it1.read().is_01() || !ap_const_lv12_CE.is_01())? sc_lv<1>(): (sc_biguint<12>(ap_reg_ppstg_t_V_reg_227_pp0_it1.read()) < sc_biguint<12>(ap_const_lv12_CE));
}

void bounding_box::thread_op2_assign_3_fu_350_p2() {
    op2_assign_3_fu_350_p2 = (!retval_i_cast_fu_324_p1.read().is_01() || !ap_const_lv13_1FC0.is_01())? sc_lv<13>(): (sc_bigint<13>(retval_i_cast_fu_324_p1.read()) + sc_biguint<13>(ap_const_lv13_1FC0));
}

void bounding_box::thread_op2_assign_8_fu_328_p2() {
    op2_assign_8_fu_328_p2 = (!retval_i_cast_fu_324_p1.read().is_01() || !ap_const_lv13_1FFF.is_01())? sc_lv<13>(): (sc_bigint<13>(retval_i_cast_fu_324_p1.read()) + sc_biguint<13>(ap_const_lv13_1FFF));
}

void bounding_box::thread_op2_assign_9_fu_338_p2() {
    op2_assign_9_fu_338_p2 = (!retval_i5_cast_fu_334_p1.read().is_01() || !ap_const_lv13_1FFF.is_01())? sc_lv<13>(): (sc_bigint<13>(retval_i5_cast_fu_334_p1.read()) + sc_biguint<13>(ap_const_lv13_1FFF));
}

void bounding_box::thread_op2_assign_fu_344_p2() {
    op2_assign_fu_344_p2 = (!retval_i5_cast_fu_334_p1.read().is_01() || !ap_const_lv13_1F33.is_01())? sc_lv<13>(): (sc_bigint<13>(retval_i5_cast_fu_334_p1.read()) + sc_biguint<13>(ap_const_lv13_1F33));
}

void bounding_box::thread_or_cond1_fu_436_p2() {
    or_cond1_fu_436_p2 = (not4_reg_750.read() & not6_fu_431_p2.read());
}

void bounding_box::thread_or_cond_fu_452_p2() {
    or_cond_fu_452_p2 = (p_not_fu_441_p2.read() | not_fu_446_p2.read());
}

void bounding_box::thread_p_not_fu_441_p2() {
    p_not_fu_441_p2 = (!tmp_16_reg_791.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_16_reg_791.read() != ap_const_lv8_0);
}

void bounding_box::thread_retval_i5_cast_fu_334_p1() {
    retval_i5_cast_fu_334_p1 = esl_zext<13,12>(src_cols_V_read.read());
}

void bounding_box::thread_retval_i_cast_fu_324_p1() {
    retval_i_cast_fu_324_p1 = esl_zext<13,12>(src_rows_V_read.read());
}

void bounding_box::thread_right_1_fu_557_p3() {
    right_1_fu_557_p3 = (!sel_tmp4_fu_514_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_fu_514_p2.read()[0].to_bool())? right_fu_88.read(): right_5_fu_549_p3.read());
}

void bounding_box::thread_right_3_fu_498_p3() {
    right_3_fu_498_p3 = (!tmp_7_fu_492_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_7_fu_492_p2.read()[0].to_bool())? right_6_fu_488_p1.read(): right_fu_88.read());
}

void bounding_box::thread_right_4_fu_542_p3() {
    right_4_fu_542_p3 = (!or_cond_reg_797.read()[0].is_01())? sc_lv<32>(): ((or_cond_reg_797.read()[0].to_bool())? right_fu_88.read(): right_3_fu_498_p3.read());
}

void bounding_box::thread_right_5_fu_549_p3() {
    right_5_fu_549_p3 = (!sel_tmp9_demorgan_fu_506_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp9_demorgan_fu_506_p2.read()[0].to_bool())? right_4_fu_542_p3.read(): right_fu_88.read());
}

void bounding_box::thread_right_6_fu_488_p1() {
    right_6_fu_488_p1 = esl_zext<32,12>(ap_reg_ppstg_t_V_reg_227_pp0_it2.read());
}

void bounding_box::thread_sel_tmp1_demorgan_fu_458_p2() {
    sel_tmp1_demorgan_fu_458_p2 = (p_not_fu_441_p2.read() | not_fu_446_p2.read());
}

void bounding_box::thread_sel_tmp1_fu_464_p2() {
    sel_tmp1_fu_464_p2 = (sel_tmp1_demorgan_fu_458_p2.read() ^ ap_const_lv1_1);
}

void bounding_box::thread_sel_tmp2_fu_510_p2() {
    sel_tmp2_fu_510_p2 = (ap_reg_ppstg_not9_reg_781_pp0_it2.read() & sel_tmp1_reg_806.read());
}

void bounding_box::thread_sel_tmp3_fu_405_p2() {
    sel_tmp3_fu_405_p2 = (not5_fu_396_p2.read() ^ ap_const_lv1_1);
}

void bounding_box::thread_sel_tmp4_fu_514_p2() {
    sel_tmp4_fu_514_p2 = (sel_tmp2_fu_510_p2.read() & sel_tmp3_reg_767.read());
}

void bounding_box::thread_sel_tmp6_fu_607_p3() {
    sel_tmp6_fu_607_p3 = (!ap_reg_ppstg_or_cond_reg_797_pp0_it3.read()[0].is_01())? sc_lv<32>(): ((ap_reg_ppstg_or_cond_reg_797_pp0_it3.read()[0].to_bool())? top_2_fu_100.read(): top_5_cast_fu_598_p1.read());
}

void bounding_box::thread_sel_tmp8_fu_634_p2() {
    sel_tmp8_fu_634_p2 = (tmp2_fu_629_p2.read() & sel_tmp2_reg_823.read());
}

void bounding_box::thread_sel_tmp9_demorgan_fu_506_p2() {
    sel_tmp9_demorgan_fu_506_p2 = (or_cond_reg_797.read() | ap_reg_ppstg_not9_reg_781_pp0_it2.read());
}

void bounding_box::thread_sel_tmp_fu_614_p3() {
    sel_tmp_fu_614_p3 = (!sel_tmp9_demorgan_reg_817.read()[0].is_01())? sc_lv<32>(): ((sel_tmp9_demorgan_reg_817.read()[0].to_bool())? sel_tmp6_fu_607_p3.read(): top_2_fu_100.read());
}

void bounding_box::thread_src_data_stream_0_V_read() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_772.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))))) {
        src_data_stream_0_V_read = ap_const_logic_1;
    } else {
        src_data_stream_0_V_read = ap_const_logic_0;
    }
}

void bounding_box::thread_t_V_phi_fu_231_p4() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_772.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        t_V_phi_fu_231_p4 = j_V_reg_776.read();
    } else {
        t_V_phi_fu_231_p4 = t_V_reg_227.read();
    }
}

void bounding_box::thread_tmp2_fu_629_p2() {
    tmp2_fu_629_p2 = (not5_reg_755.read() & tmp_8_fu_602_p2.read());
}

void bounding_box::thread_tmp_11_fu_265_p5() {
    tmp_11_fu_265_p5 = esl_partset<64,64,8,64,64>(guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns.read(), ap_const_lv8_1, ap_const_lv64_0, ap_const_lv64_7);
}

void bounding_box::thread_tmp_12_fu_278_p1() {
    tmp_12_fu_278_p1 = guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns_1.read().range(8-1, 0);
}

void bounding_box::thread_tmp_13_fu_303_p5() {
    tmp_13_fu_303_p5 = esl_partset<64,64,8,64,64>(guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns_1.read(), ap_const_lv8_1, ap_const_lv64_0, ap_const_lv64_7);
}

void bounding_box::thread_tmp_15_fu_586_p1() {
    tmp_15_fu_586_p1 = top_2_fu_100.read().range(12-1, 0);
}

void bounding_box::thread_tmp_3_fu_282_p2() {
    tmp_3_fu_282_p2 = (!tmp_12_fu_278_p1.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_12_fu_278_p1.read() == ap_const_lv8_0);
}

void bounding_box::thread_tmp_45_cast_fu_387_p1() {
    tmp_45_cast_fu_387_p1 = esl_zext<13,12>(t_V_5_reg_215.read());
}

void bounding_box::thread_tmp_47_cast_fu_422_p1() {
    tmp_47_cast_fu_422_p1 = esl_zext<13,12>(t_V_phi_fu_231_p4.read());
}

void bounding_box::thread_tmp_47_i_cast_fu_250_p1() {
    tmp_47_i_cast_fu_250_p1 = esl_zext<13,12>(src_rows_V_read.read());
}

void bounding_box::thread_tmp_48_i_cast_fu_260_p1() {
    tmp_48_i_cast_fu_260_p1 = esl_sext<32,13>(tmp_48_i_fu_254_p2.read());
}

void bounding_box::thread_tmp_48_i_fu_254_p2() {
    tmp_48_i_fu_254_p2 = (!tmp_47_i_cast_fu_250_p1.read().is_01() || !ap_const_lv13_1FFF.is_01())? sc_lv<13>(): (sc_bigint<13>(tmp_47_i_cast_fu_250_p1.read()) + sc_biguint<13>(ap_const_lv13_1FFF));
}

void bounding_box::thread_tmp_50_i_cast_fu_288_p1() {
    tmp_50_i_cast_fu_288_p1 = esl_zext<13,12>(src_cols_V_read.read());
}

void bounding_box::thread_tmp_51_i_cast_fu_298_p1() {
    tmp_51_i_cast_fu_298_p1 = esl_sext<32,13>(tmp_51_i_fu_292_p2.read());
}

void bounding_box::thread_tmp_51_i_fu_292_p2() {
    tmp_51_i_fu_292_p2 = (!tmp_50_i_cast_fu_288_p1.read().is_01() || !ap_const_lv13_1FFF.is_01())? sc_lv<13>(): (sc_bigint<13>(tmp_50_i_cast_fu_288_p1.read()) + sc_biguint<13>(ap_const_lv13_1FFF));
}

void bounding_box::thread_tmp_5_fu_476_p2() {
    tmp_5_fu_476_p2 = (!bottom_6_reg_760.read().is_01() || !bottom_fu_96.read().is_01())? sc_lv<1>(): (sc_biguint<32>(bottom_6_reg_760.read()) > sc_biguint<32>(bottom_fu_96.read()));
}

void bounding_box::thread_tmp_6_fu_581_p2() {
    tmp_6_fu_581_p2 = (!bottom_6_reg_760.read().is_01() || !top_2_fu_100.read().is_01())? sc_lv<1>(): (sc_biguint<32>(bottom_6_reg_760.read()) < sc_biguint<32>(top_2_fu_100.read()));
}

void bounding_box::thread_tmp_7_fu_492_p2() {
    tmp_7_fu_492_p2 = (!right_6_fu_488_p1.read().is_01() || !right_fu_88.read().is_01())? sc_lv<1>(): (sc_biguint<32>(right_6_fu_488_p1.read()) > sc_biguint<32>(right_fu_88.read()));
}

void bounding_box::thread_tmp_8_fu_602_p2() {
    tmp_8_fu_602_p2 = (!right_6_reg_811.read().is_01() || !left_1_fu_92.read().is_01())? sc_lv<1>(): (sc_biguint<32>(right_6_reg_811.read()) < sc_biguint<32>(left_1_fu_92.read()));
}

void bounding_box::thread_tmp_fu_240_p1() {
    tmp_fu_240_p1 = guard_variable_for_bounding_box_Mat_1080_1920_0_Mat_1080_1920_0_stream_unsigned_int_stream_uns.read().range(8-1, 0);
}

void bounding_box::thread_tmp_s_fu_244_p2() {
    tmp_s_fu_244_p2 = (!tmp_fu_240_p1.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_240_p1.read() == ap_const_lv8_0);
}

void bounding_box::thread_top_1_fu_621_p3() {
    top_1_fu_621_p3 = (!sel_tmp4_reg_828.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_828.read()[0].to_bool())? top_2_fu_100.read(): sel_tmp_fu_614_p3.read());
}

void bounding_box::thread_top_4_fu_590_p3() {
    top_4_fu_590_p3 = (!tmp_6_fu_581_p2.read()[0].is_01())? sc_lv<12>(): ((tmp_6_fu_581_p2.read()[0].to_bool())? t_V_5_reg_215.read(): tmp_15_fu_586_p1.read());
}

void bounding_box::thread_top_5_cast_fu_598_p1() {
    top_5_cast_fu_598_p1 = esl_zext<32,12>(top_4_fu_590_p3.read());
}

void bounding_box::thread_top_fu_316_p1() {
    top_fu_316_p1 = esl_zext<32,12>(src_rows_V_read.read());
}

void bounding_box::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint()) {
        case 0 : 
            if (!ap_sig_bdd_106.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_376_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_411_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if (((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
  !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  !((ap_sig_bdd_67.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_93.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_411_p2.read()) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}
}

