// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "draw.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic draw::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic draw::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> draw::ap_ST_st1_fsm_0 = "00";
const sc_lv<2> draw::ap_ST_st2_fsm_1 = "1";
const sc_lv<2> draw::ap_ST_pp0_stg0_fsm_2 = "10";
const sc_lv<2> draw::ap_const_lv2_0 = "00";
const sc_lv<1> draw::ap_const_lv1_0 = "0";
const sc_lv<12> draw::ap_const_lv12_0 = "000000000000";
const sc_lv<2> draw::ap_const_lv2_1 = "1";
const sc_lv<32> draw::ap_const_lv32_1 = "1";
const sc_lv<32> draw::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<12> draw::ap_const_lv12_1 = "1";
const sc_lv<32> draw::ap_const_lv32_18F = "110001111";
const sc_lv<32> draw::ap_const_lv32_190 = "110010000";
const sc_lv<8> draw::ap_const_lv8_FF = "11111111";
const sc_lv<1> draw::ap_const_lv1_1 = "1";
const sc_lv<8> draw::ap_const_lv8_64 = "1100100";
const sc_lv<8> draw::ap_const_lv8_0 = "00000000";

draw::draw(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond4_fu_227_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond4_fu_227_p2 );

    SC_METHOD(thread_ap_sig_bdd_114);
    sensitive << ( src_data_stream_0_V_empty_n );
    sensitive << ( bb_top_V_empty_n );
    sensitive << ( bb_bottom_V_empty_n );
    sensitive << ( bb_left_V_empty_n );
    sensitive << ( bb_right_V_empty_n );
    sensitive << ( err_V_empty_n );
    sensitive << ( val_V_V_empty_n );
    sensitive << ( exitcond_reg_593 );

    SC_METHOD(thread_ap_sig_bdd_132);
    sensitive << ( dst_data_stream_0_V_full_n );
    sensitive << ( dst_data_stream_1_V_full_n );
    sensitive << ( dst_data_stream_2_V_full_n );
    sensitive << ( ap_reg_ppstg_exitcond_reg_593_pp0_it3 );

    SC_METHOD(thread_ap_sig_bdd_414);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( tmp_V_fiforead_fu_136_p2 );

    SC_METHOD(thread_ap_sig_bdd_482);
    sensitive << ( or_cond_fu_268_p2 );
    sensitive << ( or_cond5_fu_291_p2 );

    SC_METHOD(thread_ap_sig_bdd_73);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_bb_bottom_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_bb_left_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_bb_right_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_bb_top_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_dst_data_stream_0_V_din);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_593_pp0_it3 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( sel_tmp10_reg_675 );
    sensitive << ( sel_tmp13_fu_489_p3 );

    SC_METHOD(thread_dst_data_stream_0_V_write);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_593_pp0_it3 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_dst_data_stream_1_V_din);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_593_pp0_it3 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( sel_tmp10_reg_675 );
    sensitive << ( sel_tmp6_fu_463_p3 );

    SC_METHOD(thread_dst_data_stream_1_V_write);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_593_pp0_it3 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_dst_data_stream_2_V_din);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_593_pp0_it3 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( sel_tmp10_reg_675 );
    sensitive << ( sel_tmp16_fu_511_p3 );

    SC_METHOD(thread_dst_data_stream_2_V_write);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_593_pp0_it3 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_err_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_exitcond4_fu_227_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( src_rows_V_read );
    sensitive << ( t_V_7_reg_194 );

    SC_METHOD(thread_exitcond_fu_242_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( src_cols_V_read );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( t_V_phi_fu_209_p4 );

    SC_METHOD(thread_extLd_fu_218_p1);
    sensitive << ( state );

    SC_METHOD(thread_i_V_fu_232_p2);
    sensitive << ( t_V_7_reg_194 );

    SC_METHOD(thread_j_V_fu_247_p2);
    sensitive << ( t_V_phi_fu_209_p4 );

    SC_METHOD(thread_or_cond5_fu_291_p2);
    sensitive << ( tmp_8_fu_279_p2 );
    sensitive << ( tmp_1_fu_285_p2 );

    SC_METHOD(thread_or_cond7_fu_343_p2);
    sensitive << ( tmp_4_reg_618 );
    sensitive << ( tmp2_reg_623 );

    SC_METHOD(thread_or_cond_fu_268_p2);
    sensitive << ( p_not_fu_256_p2 );
    sensitive << ( tmp_7_fu_262_p2 );

    SC_METHOD(thread_p_not_fu_256_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( tmp_V_fiforead_fu_136_p2 );
    sensitive << ( state_loc_2_fu_104 );

    SC_METHOD(thread_pixel_out_val_0_1_fu_497_p3);
    sensitive << ( sel_tmp10_reg_675 );
    sensitive << ( sel_tmp13_fu_489_p3 );

    SC_METHOD(thread_pixel_out_val_1_1_fu_471_p3);
    sensitive << ( sel_tmp10_reg_675 );
    sensitive << ( sel_tmp6_fu_463_p3 );

    SC_METHOD(thread_pixel_out_val_2_1_fu_519_p3);
    sensitive << ( sel_tmp10_reg_675 );
    sensitive << ( sel_tmp16_fu_511_p3 );

    SC_METHOD(thread_sel_tmp10_fu_424_p2);
    sensitive << ( tmp_16_reg_639 );
    sensitive << ( sel_tmp9_fu_419_p2 );

    SC_METHOD(thread_sel_tmp11_fu_479_p3);
    sensitive << ( tmp_19_reg_668 );
    sensitive << ( pixel_out_val_0_fu_96 );

    SC_METHOD(thread_sel_tmp13_fu_489_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppstg_exitcond_reg_593_pp0_it3 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3 );
    sensitive << ( sel_tmp10_reg_675 );

    SC_METHOD(thread_sel_tmp13_fu_489_p3);
    sensitive << ( tmp_20_fu_459_p2 );
    sensitive << ( sel_tmp13_fu_489_p1 );
    sensitive << ( sel_tmp11_fu_479_p3 );

    SC_METHOD(thread_sel_tmp14_fu_429_p3);
    sensitive << ( sel_tmp2_fu_400_p2 );

    SC_METHOD(thread_sel_tmp15_fu_505_p3);
    sensitive << ( tmp_19_reg_668 );
    sensitive << ( sel_tmp14_reg_682 );
    sensitive << ( pixel_out_val_2_fu_92 );

    SC_METHOD(thread_sel_tmp16_fu_511_p3);
    sensitive << ( tmp_20_fu_459_p2 );
    sensitive << ( sel_tmp5_fu_452_p3 );
    sensitive << ( sel_tmp15_fu_505_p3 );

    SC_METHOD(thread_sel_tmp1_fu_395_p2);
    sensitive << ( ap_reg_ppstg_tmp_3_reg_611_pp0_it2 );

    SC_METHOD(thread_sel_tmp2_fu_400_p2);
    sensitive << ( or_cond7_reg_634 );
    sensitive << ( sel_tmp1_fu_395_p2 );

    SC_METHOD(thread_sel_tmp3_demorgan_fu_359_p2);
    sensitive << ( tmp_3_reg_611 );
    sensitive << ( or_cond7_fu_343_p2 );

    SC_METHOD(thread_sel_tmp3_fu_446_p3);
    sensitive << ( sel_tmp9_cast_reg_663 );
    sensitive << ( tmp_19_reg_668 );
    sensitive << ( pixel_out_val_1_fu_100 );

    SC_METHOD(thread_sel_tmp4_fu_375_p2);
    sensitive << ( tmp_15_reg_628 );
    sensitive << ( sel_tmp_fu_369_p2 );

    SC_METHOD(thread_sel_tmp5_demorgan_fu_364_p2);
    sensitive << ( tmp_15_reg_628 );
    sensitive << ( sel_tmp3_demorgan_fu_359_p2 );

    SC_METHOD(thread_sel_tmp5_fu_452_p3);
    sensitive << ( ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3 );

    SC_METHOD(thread_sel_tmp6_fu_463_p3);
    sensitive << ( tmp_20_fu_459_p2 );
    sensitive << ( sel_tmp5_fu_452_p3 );
    sensitive << ( sel_tmp3_fu_446_p3 );

    SC_METHOD(thread_sel_tmp7_demorgan_fu_380_p2);
    sensitive << ( tmp_16_reg_639 );
    sensitive << ( sel_tmp5_demorgan_reg_650 );

    SC_METHOD(thread_sel_tmp7_fu_384_p2);
    sensitive << ( sel_tmp7_demorgan_fu_380_p2 );

    SC_METHOD(thread_sel_tmp8_fu_390_p2);
    sensitive << ( tmp_17_reg_645 );
    sensitive << ( sel_tmp7_fu_384_p2 );

    SC_METHOD(thread_sel_tmp9_cast_fu_405_p3);
    sensitive << ( sel_tmp2_fu_400_p2 );

    SC_METHOD(thread_sel_tmp9_fu_419_p2);
    sensitive << ( sel_tmp5_demorgan_reg_650 );

    SC_METHOD(thread_sel_tmp_fu_369_p2);
    sensitive << ( sel_tmp3_demorgan_fu_359_p2 );

    SC_METHOD(thread_src_data_stream_0_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_t_V_phi_fu_209_p4);
    sensitive << ( ap_CS_fsm );
    sensitive << ( t_V_reg_205 );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( j_V_reg_597 );

    SC_METHOD(thread_tmp2_fu_328_p2);
    sensitive << ( tmp_5_fu_318_p2 );
    sensitive << ( tmp_6_fu_323_p2 );

    SC_METHOD(thread_tmp_15_fu_334_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( src_data_stream_0_V_dout );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_tmp_16_fu_347_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_593_pp0_it1 );
    sensitive << ( state_loc_2_fu_104 );

    SC_METHOD(thread_tmp_17_fu_353_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_593_pp0_it1 );
    sensitive << ( state_loc_2_fu_104 );

    SC_METHOD(thread_tmp_19_fu_413_p2);
    sensitive << ( sel_tmp2_fu_400_p2 );
    sensitive << ( sel_tmp8_fu_390_p2 );

    SC_METHOD(thread_tmp_1_fu_285_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( err_V_dout );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( tmp_V_fiforead_fu_136_p2 );
    sensitive << ( or_cond_fu_268_p2 );

    SC_METHOD(thread_tmp_20_fu_459_p2);
    sensitive << ( ap_reg_ppstg_tmp_3_reg_611_pp0_it3 );
    sensitive << ( ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3 );

    SC_METHOD(thread_tmp_2_fu_302_p1);
    sensitive << ( t_V_reg_205 );

    SC_METHOD(thread_tmp_3_fu_306_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( bb_left_V_dout );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( tmp_2_fu_302_p1 );

    SC_METHOD(thread_tmp_4_fu_312_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( bb_right_V_dout );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( tmp_2_fu_302_p1 );

    SC_METHOD(thread_tmp_5_fu_318_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( bb_top_V_dout );
    sensitive << ( tmp_s_reg_587 );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_tmp_6_fu_323_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( bb_bottom_V_dout );
    sensitive << ( tmp_s_reg_587 );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_tmp_7_fu_262_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( err_V_dout );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( tmp_V_fiforead_fu_136_p2 );

    SC_METHOD(thread_tmp_8_fu_279_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( tmp_V_fiforead_fu_136_p2 );
    sensitive << ( or_cond_fu_268_p2 );
    sensitive << ( state_loc_2_fu_104 );

    SC_METHOD(thread_tmp_V_fiforead_fu_136_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( val_V_V_dout );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_tmp_s_fu_238_p1);
    sensitive << ( t_V_7_reg_194 );

    SC_METHOD(thread_val_V_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_593 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_73 );
    sensitive << ( exitcond4_fu_227_p2 );
    sensitive << ( exitcond_fu_242_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_sig_bdd_132 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00";
    state = "00";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "draw_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    const char* dump_vcd = std::getenv("AP_WRITE_VCD");
    if (dump_vcd && string(dump_vcd) == "1" ) {
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, src_rows_V_read, "(port)src_rows_V_read");
    sc_trace(mVcdFile, src_cols_V_read, "(port)src_cols_V_read");
    sc_trace(mVcdFile, src_data_stream_0_V_dout, "(port)src_data_stream_0_V_dout");
    sc_trace(mVcdFile, src_data_stream_0_V_empty_n, "(port)src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, src_data_stream_0_V_read, "(port)src_data_stream_0_V_read");
    sc_trace(mVcdFile, dst_data_stream_0_V_din, "(port)dst_data_stream_0_V_din");
    sc_trace(mVcdFile, dst_data_stream_0_V_full_n, "(port)dst_data_stream_0_V_full_n");
    sc_trace(mVcdFile, dst_data_stream_0_V_write, "(port)dst_data_stream_0_V_write");
    sc_trace(mVcdFile, dst_data_stream_1_V_din, "(port)dst_data_stream_1_V_din");
    sc_trace(mVcdFile, dst_data_stream_1_V_full_n, "(port)dst_data_stream_1_V_full_n");
    sc_trace(mVcdFile, dst_data_stream_1_V_write, "(port)dst_data_stream_1_V_write");
    sc_trace(mVcdFile, dst_data_stream_2_V_din, "(port)dst_data_stream_2_V_din");
    sc_trace(mVcdFile, dst_data_stream_2_V_full_n, "(port)dst_data_stream_2_V_full_n");
    sc_trace(mVcdFile, dst_data_stream_2_V_write, "(port)dst_data_stream_2_V_write");
    sc_trace(mVcdFile, bb_top_V_dout, "(port)bb_top_V_dout");
    sc_trace(mVcdFile, bb_top_V_empty_n, "(port)bb_top_V_empty_n");
    sc_trace(mVcdFile, bb_top_V_read, "(port)bb_top_V_read");
    sc_trace(mVcdFile, bb_bottom_V_dout, "(port)bb_bottom_V_dout");
    sc_trace(mVcdFile, bb_bottom_V_empty_n, "(port)bb_bottom_V_empty_n");
    sc_trace(mVcdFile, bb_bottom_V_read, "(port)bb_bottom_V_read");
    sc_trace(mVcdFile, bb_left_V_dout, "(port)bb_left_V_dout");
    sc_trace(mVcdFile, bb_left_V_empty_n, "(port)bb_left_V_empty_n");
    sc_trace(mVcdFile, bb_left_V_read, "(port)bb_left_V_read");
    sc_trace(mVcdFile, bb_right_V_dout, "(port)bb_right_V_dout");
    sc_trace(mVcdFile, bb_right_V_empty_n, "(port)bb_right_V_empty_n");
    sc_trace(mVcdFile, bb_right_V_read, "(port)bb_right_V_read");
    sc_trace(mVcdFile, err_V_dout, "(port)err_V_dout");
    sc_trace(mVcdFile, err_V_empty_n, "(port)err_V_empty_n");
    sc_trace(mVcdFile, err_V_read, "(port)err_V_read");
    sc_trace(mVcdFile, val_V_V_dout, "(port)val_V_V_dout");
    sc_trace(mVcdFile, val_V_V_empty_n, "(port)val_V_V_empty_n");
    sc_trace(mVcdFile, val_V_V_read, "(port)val_V_V_read");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, state, "state");
    sc_trace(mVcdFile, t_V_reg_205, "t_V_reg_205");
    sc_trace(mVcdFile, ap_sig_bdd_73, "ap_sig_bdd_73");
    sc_trace(mVcdFile, i_V_fu_232_p2, "i_V_fu_232_p2");
    sc_trace(mVcdFile, i_V_reg_582, "i_V_reg_582");
    sc_trace(mVcdFile, tmp_s_fu_238_p1, "tmp_s_fu_238_p1");
    sc_trace(mVcdFile, tmp_s_reg_587, "tmp_s_reg_587");
    sc_trace(mVcdFile, exitcond4_fu_227_p2, "exitcond4_fu_227_p2");
    sc_trace(mVcdFile, exitcond_fu_242_p2, "exitcond_fu_242_p2");
    sc_trace(mVcdFile, exitcond_reg_593, "exitcond_reg_593");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_sig_bdd_114, "ap_sig_bdd_114");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_593_pp0_it3, "ap_reg_ppstg_exitcond_reg_593_pp0_it3");
    sc_trace(mVcdFile, ap_sig_bdd_132, "ap_sig_bdd_132");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_593_pp0_it1, "ap_reg_ppstg_exitcond_reg_593_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_593_pp0_it2, "ap_reg_ppstg_exitcond_reg_593_pp0_it2");
    sc_trace(mVcdFile, j_V_fu_247_p2, "j_V_fu_247_p2");
    sc_trace(mVcdFile, j_V_reg_597, "j_V_reg_597");
    sc_trace(mVcdFile, tmp_3_fu_306_p2, "tmp_3_fu_306_p2");
    sc_trace(mVcdFile, tmp_3_reg_611, "tmp_3_reg_611");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_3_reg_611_pp0_it2, "ap_reg_ppstg_tmp_3_reg_611_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_3_reg_611_pp0_it3, "ap_reg_ppstg_tmp_3_reg_611_pp0_it3");
    sc_trace(mVcdFile, tmp_4_fu_312_p2, "tmp_4_fu_312_p2");
    sc_trace(mVcdFile, tmp_4_reg_618, "tmp_4_reg_618");
    sc_trace(mVcdFile, tmp2_fu_328_p2, "tmp2_fu_328_p2");
    sc_trace(mVcdFile, tmp2_reg_623, "tmp2_reg_623");
    sc_trace(mVcdFile, tmp_15_fu_334_p2, "tmp_15_fu_334_p2");
    sc_trace(mVcdFile, tmp_15_reg_628, "tmp_15_reg_628");
    sc_trace(mVcdFile, or_cond7_fu_343_p2, "or_cond7_fu_343_p2");
    sc_trace(mVcdFile, or_cond7_reg_634, "or_cond7_reg_634");
    sc_trace(mVcdFile, tmp_16_fu_347_p2, "tmp_16_fu_347_p2");
    sc_trace(mVcdFile, tmp_16_reg_639, "tmp_16_reg_639");
    sc_trace(mVcdFile, tmp_17_fu_353_p2, "tmp_17_fu_353_p2");
    sc_trace(mVcdFile, tmp_17_reg_645, "tmp_17_reg_645");
    sc_trace(mVcdFile, sel_tmp5_demorgan_fu_364_p2, "sel_tmp5_demorgan_fu_364_p2");
    sc_trace(mVcdFile, sel_tmp5_demorgan_reg_650, "sel_tmp5_demorgan_reg_650");
    sc_trace(mVcdFile, sel_tmp4_fu_375_p2, "sel_tmp4_fu_375_p2");
    sc_trace(mVcdFile, sel_tmp4_reg_656, "sel_tmp4_reg_656");
    sc_trace(mVcdFile, ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3, "ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3");
    sc_trace(mVcdFile, sel_tmp9_cast_fu_405_p3, "sel_tmp9_cast_fu_405_p3");
    sc_trace(mVcdFile, sel_tmp9_cast_reg_663, "sel_tmp9_cast_reg_663");
    sc_trace(mVcdFile, tmp_19_fu_413_p2, "tmp_19_fu_413_p2");
    sc_trace(mVcdFile, tmp_19_reg_668, "tmp_19_reg_668");
    sc_trace(mVcdFile, sel_tmp10_fu_424_p2, "sel_tmp10_fu_424_p2");
    sc_trace(mVcdFile, sel_tmp10_reg_675, "sel_tmp10_reg_675");
    sc_trace(mVcdFile, sel_tmp14_fu_429_p3, "sel_tmp14_fu_429_p3");
    sc_trace(mVcdFile, sel_tmp14_reg_682, "sel_tmp14_reg_682");
    sc_trace(mVcdFile, t_V_7_reg_194, "t_V_7_reg_194");
    sc_trace(mVcdFile, t_V_phi_fu_209_p4, "t_V_phi_fu_209_p4");
    sc_trace(mVcdFile, tmp_V_fiforead_fu_136_p2, "tmp_V_fiforead_fu_136_p2");
    sc_trace(mVcdFile, pixel_out_val_0_1_fu_497_p3, "pixel_out_val_0_1_fu_497_p3");
    sc_trace(mVcdFile, pixel_out_val_1_1_fu_471_p3, "pixel_out_val_1_1_fu_471_p3");
    sc_trace(mVcdFile, pixel_out_val_2_1_fu_519_p3, "pixel_out_val_2_1_fu_519_p3");
    sc_trace(mVcdFile, or_cond_fu_268_p2, "or_cond_fu_268_p2");
    sc_trace(mVcdFile, or_cond5_fu_291_p2, "or_cond5_fu_291_p2");
    sc_trace(mVcdFile, pixel_out_val_2_fu_92, "pixel_out_val_2_fu_92");
    sc_trace(mVcdFile, pixel_out_val_0_fu_96, "pixel_out_val_0_fu_96");
    sc_trace(mVcdFile, pixel_out_val_1_fu_100, "pixel_out_val_1_fu_100");
    sc_trace(mVcdFile, state_loc_2_fu_104, "state_loc_2_fu_104");
    sc_trace(mVcdFile, extLd_fu_218_p1, "extLd_fu_218_p1");
    sc_trace(mVcdFile, p_not_fu_256_p2, "p_not_fu_256_p2");
    sc_trace(mVcdFile, tmp_7_fu_262_p2, "tmp_7_fu_262_p2");
    sc_trace(mVcdFile, tmp_8_fu_279_p2, "tmp_8_fu_279_p2");
    sc_trace(mVcdFile, tmp_1_fu_285_p2, "tmp_1_fu_285_p2");
    sc_trace(mVcdFile, tmp_2_fu_302_p1, "tmp_2_fu_302_p1");
    sc_trace(mVcdFile, tmp_5_fu_318_p2, "tmp_5_fu_318_p2");
    sc_trace(mVcdFile, tmp_6_fu_323_p2, "tmp_6_fu_323_p2");
    sc_trace(mVcdFile, sel_tmp3_demorgan_fu_359_p2, "sel_tmp3_demorgan_fu_359_p2");
    sc_trace(mVcdFile, sel_tmp_fu_369_p2, "sel_tmp_fu_369_p2");
    sc_trace(mVcdFile, sel_tmp7_demorgan_fu_380_p2, "sel_tmp7_demorgan_fu_380_p2");
    sc_trace(mVcdFile, sel_tmp7_fu_384_p2, "sel_tmp7_fu_384_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_395_p2, "sel_tmp1_fu_395_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_400_p2, "sel_tmp2_fu_400_p2");
    sc_trace(mVcdFile, sel_tmp8_fu_390_p2, "sel_tmp8_fu_390_p2");
    sc_trace(mVcdFile, sel_tmp9_fu_419_p2, "sel_tmp9_fu_419_p2");
    sc_trace(mVcdFile, tmp_20_fu_459_p2, "tmp_20_fu_459_p2");
    sc_trace(mVcdFile, sel_tmp5_fu_452_p3, "sel_tmp5_fu_452_p3");
    sc_trace(mVcdFile, sel_tmp3_fu_446_p3, "sel_tmp3_fu_446_p3");
    sc_trace(mVcdFile, sel_tmp6_fu_463_p3, "sel_tmp6_fu_463_p3");
    sc_trace(mVcdFile, sel_tmp13_fu_489_p1, "sel_tmp13_fu_489_p1");
    sc_trace(mVcdFile, sel_tmp11_fu_479_p3, "sel_tmp11_fu_479_p3");
    sc_trace(mVcdFile, sel_tmp13_fu_489_p3, "sel_tmp13_fu_489_p3");
    sc_trace(mVcdFile, sel_tmp15_fu_505_p3, "sel_tmp15_fu_505_p3");
    sc_trace(mVcdFile, sel_tmp16_fu_511_p3, "sel_tmp16_fu_511_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_bdd_482, "ap_sig_bdd_482");
    sc_trace(mVcdFile, ap_sig_bdd_414, "ap_sig_bdd_414");

    }
}

draw::~draw() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void draw::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                    !esl_seteq<1,1,1>(exitcond4_fu_227_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
             !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_242_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                    esl_seteq<1,1,1>(exitcond4_fu_227_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
             !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_242_p2.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                     esl_seteq<1,1,1>(exitcond4_fu_227_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
                     !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_242_p2.read())))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
             !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        } else if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                    esl_seteq<1,1,1>(exitcond4_fu_227_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
             !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        } else if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                    esl_seteq<1,1,1>(exitcond4_fu_227_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
             !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        } else if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                    esl_seteq<1,1,1>(exitcond4_fu_227_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
        }
    }
    if (ap_sig_bdd_414.read()) {
        if (ap_sig_bdd_482.read()) {
            state = ap_const_lv2_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_268_p2.read())) {
            state = ap_const_lv2_1;
        }
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_V_fiforead_fu_136_p2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_268_p2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_291_p2.read()))) {
        state_loc_2_fu_104 = ap_const_lv32_0;
    } else if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
                !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_V_fiforead_fu_136_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_268_p2.read()))) {
        state_loc_2_fu_104 = ap_const_lv32_1;
    } else if ((esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !ap_sig_bdd_73.read())) {
        state_loc_2_fu_104 = extLd_fu_218_p1.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_242_p2.read()))) {
        t_V_7_reg_194 = i_V_reg_582.read();
    } else if ((esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !ap_sig_bdd_73.read())) {
        t_V_7_reg_194 = ap_const_lv12_0;
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        t_V_reg_205 = j_V_reg_597.read();
    } else if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(exitcond4_fu_227_p2.read(), ap_const_lv1_0))) {
        t_V_reg_205 = ap_const_lv12_0;
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        ap_reg_ppstg_exitcond_reg_593_pp0_it1 = exitcond_reg_593.read();
        ap_reg_ppstg_exitcond_reg_593_pp0_it2 = ap_reg_ppstg_exitcond_reg_593_pp0_it1.read();
        ap_reg_ppstg_exitcond_reg_593_pp0_it3 = ap_reg_ppstg_exitcond_reg_593_pp0_it2.read();
        ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3 = sel_tmp4_reg_656.read();
        ap_reg_ppstg_tmp_3_reg_611_pp0_it2 = tmp_3_reg_611.read();
        ap_reg_ppstg_tmp_3_reg_611_pp0_it3 = ap_reg_ppstg_tmp_3_reg_611_pp0_it2.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        exitcond_reg_593 = exitcond_fu_242_p2.read();
        j_V_reg_597 = j_V_fu_247_p2.read();
    }
    if (esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        i_V_reg_582 = i_V_fu_232_p2.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_593_pp0_it1.read()))) {
        or_cond7_reg_634 = or_cond7_fu_343_p2.read();
        sel_tmp4_reg_656 = sel_tmp4_fu_375_p2.read();
        sel_tmp5_demorgan_reg_650 = sel_tmp5_demorgan_fu_364_p2.read();
        tmp_16_reg_639 = tmp_16_fu_347_p2.read();
        tmp_17_reg_645 = tmp_17_fu_353_p2.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_593_pp0_it3.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        pixel_out_val_0_fu_96 = pixel_out_val_0_1_fu_497_p3.read();
        pixel_out_val_1_fu_100 = pixel_out_val_1_1_fu_471_p3.read();
        pixel_out_val_2_fu_92 = pixel_out_val_2_1_fu_519_p3.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_593_pp0_it2.read()))) {
        sel_tmp10_reg_675 = sel_tmp10_fu_424_p2.read();
        sel_tmp14_reg_682 = sel_tmp14_fu_429_p3.read();
        sel_tmp9_cast_reg_663 = sel_tmp9_cast_fu_405_p3.read();
        tmp_19_reg_668 = tmp_19_fu_413_p2.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        tmp2_reg_623 = tmp2_fu_328_p2.read();
        tmp_15_reg_628 = tmp_15_fu_334_p2.read();
        tmp_3_reg_611 = tmp_3_fu_306_p2.read();
        tmp_4_reg_618 = tmp_4_fu_312_p2.read();
    }
    if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && esl_seteq<1,1,1>(exitcond4_fu_227_p2.read(), ap_const_lv1_0))) {
        tmp_s_reg_587 = tmp_s_fu_238_p1.read();
    }
}

void draw::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(exitcond4_fu_227_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void draw::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,2,2>(ap_ST_st1_fsm_0, ap_CS_fsm.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void draw::thread_ap_ready() {
    if ((esl_seteq<1,2,2>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(exitcond4_fu_227_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void draw::thread_ap_sig_bdd_114() {
    ap_sig_bdd_114 = ((esl_seteq<1,1,1>(src_data_stream_0_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
  esl_seteq<1,1,1>(err_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
  esl_seteq<1,1,1>(val_V_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
  esl_seteq<1,1,1>(bb_top_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
  esl_seteq<1,1,1>(bb_bottom_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
  esl_seteq<1,1,1>(bb_left_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
  esl_seteq<1,1,1>(bb_right_V_empty_n.read(), ap_const_logic_0)));
}

void draw::thread_ap_sig_bdd_132() {
    ap_sig_bdd_132 = ((esl_seteq<1,1,1>(dst_data_stream_0_V_full_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_593_pp0_it3.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_593_pp0_it3.read()) && 
  esl_seteq<1,1,1>(dst_data_stream_1_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_593_pp0_it3.read()) && 
  esl_seteq<1,1,1>(dst_data_stream_2_V_full_n.read(), ap_const_logic_0)));
}

void draw::thread_ap_sig_bdd_414() {
    ap_sig_bdd_414 = (esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_V_fiforead_fu_136_p2.read()));
}

void draw::thread_ap_sig_bdd_482() {
    ap_sig_bdd_482 = (!esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_268_p2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_291_p2.read()));
}

void draw::thread_ap_sig_bdd_73() {
    ap_sig_bdd_73 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void draw::thread_bb_bottom_V_read() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        bb_bottom_V_read = ap_const_logic_1;
    } else {
        bb_bottom_V_read = ap_const_logic_0;
    }
}

void draw::thread_bb_left_V_read() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        bb_left_V_read = ap_const_logic_1;
    } else {
        bb_left_V_read = ap_const_logic_0;
    }
}

void draw::thread_bb_right_V_read() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        bb_right_V_read = ap_const_logic_1;
    } else {
        bb_right_V_read = ap_const_logic_0;
    }
}

void draw::thread_bb_top_V_read() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        bb_top_V_read = ap_const_logic_1;
    } else {
        bb_top_V_read = ap_const_logic_0;
    }
}

void draw::thread_dst_data_stream_0_V_din() {
    dst_data_stream_0_V_din = (!sel_tmp10_reg_675.read()[0].is_01())? sc_lv<8>(): ((sel_tmp10_reg_675.read()[0].to_bool())? ap_const_lv8_0: sel_tmp13_fu_489_p3.read());
}

void draw::thread_dst_data_stream_0_V_write() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_593_pp0_it3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
         !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        dst_data_stream_0_V_write = ap_const_logic_1;
    } else {
        dst_data_stream_0_V_write = ap_const_logic_0;
    }
}

void draw::thread_dst_data_stream_1_V_din() {
    dst_data_stream_1_V_din = (!sel_tmp10_reg_675.read()[0].is_01())? sc_lv<8>(): ((sel_tmp10_reg_675.read()[0].to_bool())? ap_const_lv8_FF: sel_tmp6_fu_463_p3.read());
}

void draw::thread_dst_data_stream_1_V_write() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_593_pp0_it3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
         !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        dst_data_stream_1_V_write = ap_const_logic_1;
    } else {
        dst_data_stream_1_V_write = ap_const_logic_0;
    }
}

void draw::thread_dst_data_stream_2_V_din() {
    dst_data_stream_2_V_din = (!sel_tmp10_reg_675.read()[0].is_01())? sc_lv<8>(): ((sel_tmp10_reg_675.read()[0].to_bool())? ap_const_lv8_0: sel_tmp16_fu_511_p3.read());
}

void draw::thread_dst_data_stream_2_V_write() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_593_pp0_it3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
         !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        dst_data_stream_2_V_write = ap_const_logic_1;
    } else {
        dst_data_stream_2_V_write = ap_const_logic_0;
    }
}

void draw::thread_err_V_read() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        err_V_read = ap_const_logic_1;
    } else {
        err_V_read = ap_const_logic_0;
    }
}

void draw::thread_exitcond4_fu_227_p2() {
    exitcond4_fu_227_p2 = (!t_V_7_reg_194.read().is_01() || !src_rows_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_7_reg_194.read() == src_rows_V_read.read());
}

void draw::thread_exitcond_fu_242_p2() {
    exitcond_fu_242_p2 = (!t_V_phi_fu_209_p4.read().is_01() || !src_cols_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_phi_fu_209_p4.read() == src_cols_V_read.read());
}

void draw::thread_extLd_fu_218_p1() {
    extLd_fu_218_p1 = esl_zext<32,2>(state.read());
}

void draw::thread_i_V_fu_232_p2() {
    i_V_fu_232_p2 = (!t_V_7_reg_194.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_bigint<12>(t_V_7_reg_194.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void draw::thread_j_V_fu_247_p2() {
    j_V_fu_247_p2 = (!t_V_phi_fu_209_p4.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_bigint<12>(t_V_phi_fu_209_p4.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void draw::thread_or_cond5_fu_291_p2() {
    or_cond5_fu_291_p2 = (tmp_8_fu_279_p2.read() & tmp_1_fu_285_p2.read());
}

void draw::thread_or_cond7_fu_343_p2() {
    or_cond7_fu_343_p2 = (tmp2_reg_623.read() | tmp_4_reg_618.read());
}

void draw::thread_or_cond_fu_268_p2() {
    or_cond_fu_268_p2 = (p_not_fu_256_p2.read() | tmp_7_fu_262_p2.read());
}

void draw::thread_p_not_fu_256_p2() {
    p_not_fu_256_p2 = (!state_loc_2_fu_104.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(state_loc_2_fu_104.read() != ap_const_lv32_0);
}

void draw::thread_pixel_out_val_0_1_fu_497_p3() {
    pixel_out_val_0_1_fu_497_p3 = (!sel_tmp10_reg_675.read()[0].is_01())? sc_lv<8>(): ((sel_tmp10_reg_675.read()[0].to_bool())? ap_const_lv8_0: sel_tmp13_fu_489_p3.read());
}

void draw::thread_pixel_out_val_1_1_fu_471_p3() {
    pixel_out_val_1_1_fu_471_p3 = (!sel_tmp10_reg_675.read()[0].is_01())? sc_lv<8>(): ((sel_tmp10_reg_675.read()[0].to_bool())? ap_const_lv8_FF: sel_tmp6_fu_463_p3.read());
}

void draw::thread_pixel_out_val_2_1_fu_519_p3() {
    pixel_out_val_2_1_fu_519_p3 = (!sel_tmp10_reg_675.read()[0].is_01())? sc_lv<8>(): ((sel_tmp10_reg_675.read()[0].to_bool())? ap_const_lv8_0: sel_tmp16_fu_511_p3.read());
}

void draw::thread_sel_tmp10_fu_424_p2() {
    sel_tmp10_fu_424_p2 = (tmp_16_reg_639.read() & sel_tmp9_fu_419_p2.read());
}

void draw::thread_sel_tmp11_fu_479_p3() {
    sel_tmp11_fu_479_p3 = (!tmp_19_reg_668.read()[0].is_01())? sc_lv<8>(): ((tmp_19_reg_668.read()[0].to_bool())? ap_const_lv8_0: pixel_out_val_0_fu_96.read());
}

void draw::thread_sel_tmp13_fu_489_p1() {
    sel_tmp13_fu_489_p1 = esl_sext<8,1>(ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3.read());
}

void draw::thread_sel_tmp13_fu_489_p3() {
    sel_tmp13_fu_489_p3 = (!tmp_20_fu_459_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_20_fu_459_p2.read()[0].to_bool())? sel_tmp13_fu_489_p1.read(): sel_tmp11_fu_479_p3.read());
}

void draw::thread_sel_tmp14_fu_429_p3() {
    sel_tmp14_fu_429_p3 = (!sel_tmp2_fu_400_p2.read()[0].is_01())? sc_lv<8>(): ((sel_tmp2_fu_400_p2.read()[0].to_bool())? ap_const_lv8_64: ap_const_lv8_FF);
}

void draw::thread_sel_tmp15_fu_505_p3() {
    sel_tmp15_fu_505_p3 = (!tmp_19_reg_668.read()[0].is_01())? sc_lv<8>(): ((tmp_19_reg_668.read()[0].to_bool())? sel_tmp14_reg_682.read(): pixel_out_val_2_fu_92.read());
}

void draw::thread_sel_tmp16_fu_511_p3() {
    sel_tmp16_fu_511_p3 = (!tmp_20_fu_459_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_20_fu_459_p2.read()[0].to_bool())? sel_tmp5_fu_452_p3.read(): sel_tmp15_fu_505_p3.read());
}

void draw::thread_sel_tmp1_fu_395_p2() {
    sel_tmp1_fu_395_p2 = (ap_reg_ppstg_tmp_3_reg_611_pp0_it2.read() ^ ap_const_lv1_1);
}

void draw::thread_sel_tmp2_fu_400_p2() {
    sel_tmp2_fu_400_p2 = (or_cond7_reg_634.read() & sel_tmp1_fu_395_p2.read());
}

void draw::thread_sel_tmp3_demorgan_fu_359_p2() {
    sel_tmp3_demorgan_fu_359_p2 = (tmp_3_reg_611.read() | or_cond7_fu_343_p2.read());
}

void draw::thread_sel_tmp3_fu_446_p3() {
    sel_tmp3_fu_446_p3 = (!tmp_19_reg_668.read()[0].is_01())? sc_lv<8>(): ((tmp_19_reg_668.read()[0].to_bool())? sel_tmp9_cast_reg_663.read(): pixel_out_val_1_fu_100.read());
}

void draw::thread_sel_tmp4_fu_375_p2() {
    sel_tmp4_fu_375_p2 = (tmp_15_reg_628.read() & sel_tmp_fu_369_p2.read());
}

void draw::thread_sel_tmp5_demorgan_fu_364_p2() {
    sel_tmp5_demorgan_fu_364_p2 = (sel_tmp3_demorgan_fu_359_p2.read() | tmp_15_reg_628.read());
}

void draw::thread_sel_tmp5_fu_452_p3() {
    sel_tmp5_fu_452_p3 = (!ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3.read()[0].is_01())? sc_lv<8>(): ((ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_64);
}

void draw::thread_sel_tmp6_fu_463_p3() {
    sel_tmp6_fu_463_p3 = (!tmp_20_fu_459_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_20_fu_459_p2.read()[0].to_bool())? sel_tmp5_fu_452_p3.read(): sel_tmp3_fu_446_p3.read());
}

void draw::thread_sel_tmp7_demorgan_fu_380_p2() {
    sel_tmp7_demorgan_fu_380_p2 = (sel_tmp5_demorgan_reg_650.read() | tmp_16_reg_639.read());
}

void draw::thread_sel_tmp7_fu_384_p2() {
    sel_tmp7_fu_384_p2 = (sel_tmp7_demorgan_fu_380_p2.read() ^ ap_const_lv1_1);
}

void draw::thread_sel_tmp8_fu_390_p2() {
    sel_tmp8_fu_390_p2 = (tmp_17_reg_645.read() & sel_tmp7_fu_384_p2.read());
}

void draw::thread_sel_tmp9_cast_fu_405_p3() {
    sel_tmp9_cast_fu_405_p3 = (!sel_tmp2_fu_400_p2.read()[0].is_01())? sc_lv<8>(): ((sel_tmp2_fu_400_p2.read()[0].to_bool())? ap_const_lv8_64: ap_const_lv8_0);
}

void draw::thread_sel_tmp9_fu_419_p2() {
    sel_tmp9_fu_419_p2 = (sel_tmp5_demorgan_reg_650.read() ^ ap_const_lv1_1);
}

void draw::thread_sel_tmp_fu_369_p2() {
    sel_tmp_fu_369_p2 = (sel_tmp3_demorgan_fu_359_p2.read() ^ ap_const_lv1_1);
}

void draw::thread_src_data_stream_0_V_read() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        src_data_stream_0_V_read = ap_const_logic_1;
    } else {
        src_data_stream_0_V_read = ap_const_logic_0;
    }
}

void draw::thread_t_V_phi_fu_209_p4() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        t_V_phi_fu_209_p4 = j_V_reg_597.read();
    } else {
        t_V_phi_fu_209_p4 = t_V_reg_205.read();
    }
}

void draw::thread_tmp2_fu_328_p2() {
    tmp2_fu_328_p2 = (tmp_5_fu_318_p2.read() | tmp_6_fu_323_p2.read());
}

void draw::thread_tmp_15_fu_334_p2() {
    tmp_15_fu_334_p2 = (!src_data_stream_0_V_dout.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(src_data_stream_0_V_dout.read() == ap_const_lv8_FF);
}

void draw::thread_tmp_16_fu_347_p2() {
    tmp_16_fu_347_p2 = (!state_loc_2_fu_104.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): sc_lv<1>(state_loc_2_fu_104.read() == ap_const_lv32_1);
}

void draw::thread_tmp_17_fu_353_p2() {
    tmp_17_fu_353_p2 = (!state_loc_2_fu_104.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(state_loc_2_fu_104.read() == ap_const_lv32_0);
}

void draw::thread_tmp_19_fu_413_p2() {
    tmp_19_fu_413_p2 = (sel_tmp2_fu_400_p2.read() | sel_tmp8_fu_390_p2.read());
}

void draw::thread_tmp_1_fu_285_p2() {
    tmp_1_fu_285_p2 = (!err_V_dout.read().is_01() || !ap_const_lv32_190.is_01())? sc_lv<1>(): (sc_biguint<32>(err_V_dout.read()) > sc_biguint<32>(ap_const_lv32_190));
}

void draw::thread_tmp_20_fu_459_p2() {
    tmp_20_fu_459_p2 = (ap_reg_ppstg_sel_tmp4_reg_656_pp0_it3.read() | ap_reg_ppstg_tmp_3_reg_611_pp0_it3.read());
}

void draw::thread_tmp_2_fu_302_p1() {
    tmp_2_fu_302_p1 = esl_zext<32,12>(t_V_reg_205.read());
}

void draw::thread_tmp_3_fu_306_p2() {
    tmp_3_fu_306_p2 = (!tmp_2_fu_302_p1.read().is_01() || !bb_left_V_dout.read().is_01())? sc_lv<1>(): sc_lv<1>(tmp_2_fu_302_p1.read() == bb_left_V_dout.read());
}

void draw::thread_tmp_4_fu_312_p2() {
    tmp_4_fu_312_p2 = (!tmp_2_fu_302_p1.read().is_01() || !bb_right_V_dout.read().is_01())? sc_lv<1>(): sc_lv<1>(tmp_2_fu_302_p1.read() == bb_right_V_dout.read());
}

void draw::thread_tmp_5_fu_318_p2() {
    tmp_5_fu_318_p2 = (!tmp_s_reg_587.read().is_01() || !bb_top_V_dout.read().is_01())? sc_lv<1>(): sc_lv<1>(tmp_s_reg_587.read() == bb_top_V_dout.read());
}

void draw::thread_tmp_6_fu_323_p2() {
    tmp_6_fu_323_p2 = (!tmp_s_reg_587.read().is_01() || !bb_bottom_V_dout.read().is_01())? sc_lv<1>(): sc_lv<1>(tmp_s_reg_587.read() == bb_bottom_V_dout.read());
}

void draw::thread_tmp_7_fu_262_p2() {
    tmp_7_fu_262_p2 = (!err_V_dout.read().is_01() || !ap_const_lv32_18F.is_01())? sc_lv<1>(): (sc_biguint<32>(err_V_dout.read()) > sc_biguint<32>(ap_const_lv32_18F));
}

void draw::thread_tmp_8_fu_279_p2() {
    tmp_8_fu_279_p2 = (!state_loc_2_fu_104.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): sc_lv<1>(state_loc_2_fu_104.read() == ap_const_lv32_1);
}

void draw::thread_tmp_V_fiforead_fu_136_p2() {
    tmp_V_fiforead_fu_136_p2 = val_V_V_dout.read();
}

void draw::thread_tmp_s_fu_238_p1() {
    tmp_s_fu_238_p1 = esl_zext<32,12>(t_V_7_reg_194.read());
}

void draw::thread_val_V_V_read() {
    if ((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_593.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        val_V_V_read = ap_const_logic_1;
    } else {
        val_V_V_read = ap_const_logic_0;
    }
}

void draw::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint()) {
        case 0 : 
            if (!ap_sig_bdd_73.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 1 : 
            if (!esl_seteq<1,1,1>(exitcond4_fu_227_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_242_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if (((esl_seteq<1,2,2>(ap_ST_pp0_stg0_fsm_2, ap_CS_fsm.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  !((ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_132.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_242_p2.read()) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}
}

